apiVersion: v1
kind: Secret
metadata:
    name: pollenzo-db-secret
type: Opaque
stringData:
    datasource-url: ENC[AES256_GCM,data:frbNsZnQ+UEIybsm85x2O/Noj3bpdpvP30Lv/eEjL1Gw4NtL/5bOMHFsyvBchCZ4z2/8tsNu5brgJZlIrgjisf99JbNnEdxbp7q3YBc=,iv:q4etEOh7Ogdu8qWsnOmZDwbMHxe7kDWkng81TIudP00=,tag:G8Jv8D/63zF3DaJf79qoqA==,type:str]
    username: ENC[AES256_GCM,data:lsza0D9C5t0=,iv:6c6hbyUI95JDtjfZgzEhaJNvzE+ICLoBJxTNhTnlTOo=,tag:uVj68mqLlQnp3Fpd9HEjJQ==,type:str]
    password: ENC[AES256_GCM,data:sQbbDO/sWHmex1YFYausKqVu4vw=,iv:jnhqB8aOb/vZfHxqDZmUe1P9CJMwCfo828IIMt9uj5E=,tag:L4Sda2gSJOlg2p0sw4dBNQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa1duWnpJSjV2OW5saStH
            alV3U2pNdGtyM2FUbnoySVFGR0x2c25jMmpNCnY4NWg4ajdWWGQ1bERPZjUxeGdJ
            alY3cWF6aC9zd1dPY2lJTUhtbVlvdlkKLS0tIGs0RU05dURKekVMaWo0UXZzOCtO
            OStqMFBmbm5TaFhpYnoyRFF3U0FBZWsKgLdLCvaF2LOEFDphZEuzZDT55klL/bo0
            JnPmQhHB6FpYgQTE6lRqbHB1Llps+YvnePUy5EPPZooC1ziOuLR5Bw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VktCUFFsK0dtT3MrV1R1
            YTdzTE5jWTF0VnMyTVl0QnBBeWI4V2JaM0drCm94NkFlK1BqeXZmNFJmZWhKbHEv
            TWdxL0R0a0M0Qm91MW5kajg3SWcwTG8KLS0tIEw5bFFXS2FWSFBSQVUzWGhDWStn
            UTIrQVMzMTRnY3hnd1VZQmcxUzBFNUEKTutIRSyV0R2D4WAxnvmfBY8wZlx9D8L1
            g8omOfT66eUtVSAYCgI6aYh3+bn/QMdrzy/24cAp4nBV1Wp2MSg73w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR2ttaXAxR3JFN0NibVln
            dGdiUDQ1Qmwra3ZRWkljT1RodEdmaU81VlJVCkFZYzdUMjVmcW9hWXgwRVdGWDVM
            cldPdTVXRnhHbnBtSUdEcUJDSk1tS3cKLS0tIHpPaWRIeVhrRFN5MmRodnVxeE9m
            Z0M5bHdueEg5Q1h6NnZ1azJkcXRwYm8KYbrWTWPzauhaUN/BGTxtd6iJ+oD9t2tz
            t0j8J4tNhFv30Mv9G4nwSrPBXrJQ6wwVxyFOrWT5f7FOUF1ogFGD5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWNFZG5lNDNsTGg4NTRJ
            SGFBalU1c1FqRXV3RVpablp3MDM1Z1VEM0Q0CmdPb0hMZExZTHYxbmNwbnFDVklu
            NEJvN2J4YnB2ay9wU1dDeHB0YmZwNk0KLS0tIDhYN1E0MElZOVczNnRCQTZrN1Q1
            cnJqS0kvaUEwYzk4KzlqSjcreWxnbTgK7FJa630owxRfr72RgovU87Owh3z7CMnb
            1CI2u0H4rz830jOWB9t08/FxgrIXAJQ6MY9mOu56MvcVwBY0w3bb3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T13:36:28Z"
    mac: ENC[AES256_GCM,data:zEFosNxfhqWgZkrwH/RzWCNCDPGLFgB4CdYEvlPWTUPWy7WUWRU+3B1GpHhI3QChMzbzx5dnMrCRwPgqdUX8qb49U/b1X9xRYKyp9WL/3T/pjVnUMwtsXewbrxwlEFnq2E2yTBUq65zw5/3el7O7FM7Dot9wy35ItXr5HVvunjQ=,iv:G0mWuFy6z0mzFIRvAkYKSHDQOWR2drzx53P0s589KA4=,tag:jMfD1ltOajdRdE8T/W0ByQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
