apiVersion: v1
kind: Secret
metadata:
    name: pollenzo-secret
type: Opaque
stringData:
    activemq-broker-url: ENC[AES256_GCM,data:1HqKHUzUYBL7se4PQ0tXNsZRIIFFH2lD19cP7sMTKkat8clfA4b/LcrT5ScOZ58=,iv:SIYf5DULx0DHrITbhkH+MRBZU9j5EbQsybNRgArK/r8=,tag:oMyiaAl7r0jw4R9bUrCmyQ==,type:str]
    activemq-username: ENC[AES256_GCM,data:UZ1M1ck=,iv:ACL0elzPGecZJmia7JPWiIwFkimUg0HAcBtFstsoIlU=,tag:MFzU13TESVP8q4BF5tDFeg==,type:str]
    activemq-password: ENC[AES256_GCM,data:e/PUduZiZ6/ZCol2dLB31GhEXCA=,iv:n8HVCcxwiVch8raya7o4LkJt+QDKrxi+S62rRp9oY84=,tag:VKormSciGU2QAEi87EaC+w==,type:str]
    jwt-secret-key: ENC[AES256_GCM,data:WrRXprFfhl93FeK2U/SRLsgj3Vm1PXoh3K4V0A++AJ8N6vm15uQWaF11wMqZ5GlKkeYkj8759z/c7DMMOXa4sLLCMto=,iv:f2gM32ON6PlNJnNmJU7kXuZNVs8aguHNnRWYa2N+G3I=,tag:9tZj1TkxMec9S+9tHJdCtA==,type:str]
    air-quality-token: ENC[AES256_GCM,data:l3ZpMUp342h1zDms7eC0oFGcKY/sAciSLyVhe/kiJdtBbaKyHRp2ew==,iv:ZX82empP3UBqx3nsWs0G4qWOA4d2rSLyTbbce4sKN4g=,tag:sxzyJFrUlG+aSlNPnb1GvQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNDVoYTRWR05BdUE4WGdZ
            UW05Z2ROL21ldUZyNFhWYlNlTVZrOHQydmcwCmFZb2tWYXIvbzJLMXdaUVFQVldD
            YzVTQVVGQVZDSzQ0dzBBaXkxeGVQTmMKLS0tIFZVOEVkZFprSHFlanU4WHhJLzJW
            R0hnN1ovcTJ4a1pWbG9nS1VhN3UvRUUKgwGITFQJcpUvUnCwno1Slfqe1pOQ7VwH
            BKRkb1VewPKCOvnd20PI7qCgbZPN5CjjuFfU0C8RZiyU0bGtNWudnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NS9mT2p1cWQrdUMxb1Ri
            U2phL05uTzZZN1VaSmVUbUdWcDY2dHNQcFFVCkxzQUVwTm1uRkFVSHN1U21CZTYr
            T3hZU3BzZ2p4eU5RQ1BuNGhwNEhFS1kKLS0tIGhiUWJYSDRqaXR0Z2pqR0NvMUVG
            Ti9RTHFQMWVQd2NVekw1SnJoZWg0OVkK8LDoH6ysKIw/CZ8M8z+bSAdo2JkE0/g8
            cyle7iNp2DSAmyka8CH/Uhn5+IlLu605k3D9lGh4Hwn2d4kF2360qA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK1BvdlZkNzFpRkozZGdu
            eGdaRktwc1BEdlpNVUh5aFNDL1ZMZUJYN1d3CnZZREsreWFWSlFxM000NGMzYVBj
            Zjh6T05TUFBEYWZGd2w2MjJVUUN0VEUKLS0tIEtpRVRLTVVFL3ZObCtYODdjLzVt
            YkM3Tkxqa1lYeHB0MFVFTTZVYVpCZmMKlQK1MPkN77KI4stl3gps9pfYycFa9S/e
            J434vt8MIoY0/IsgMmpKTw7POQ+W3yLWYEEas+PTIuT8n8/kyRVSTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Ty92RzZlUldCMEZLdTVS
            ZGlzeW1kT2RxRW1jOEsvR1VNMllXL05lWTJrCit5YjBQMkNqSGJnWVNvOUUzSTk4
            eWZ2TFhyWEFGU04zMytUQWYrVWtsZEEKLS0tIDVLRWhNTEQ5SVNMNVpZempYN1Jv
            QWl0T2V4cEtSZlFCamc2UjR4TTYwQUkKYvmhQ+Cn58Sxze55TiC4SHb+krarBjp/
            Hx7V7VK2V8SbIluTVr5KC63HG1w97v5Hl+si7UTCVIOUCfq5kXp9kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:41:24Z"
    mac: ENC[AES256_GCM,data:BA8JpvtRTX1wGjQoTCVjorqHpvBpWtCG6b9RRtYPITafoTT2R3RAQOqF9jaxM5820ZuB+sN1urHqXv7fWsS/V7JOSnPvyXeT0lTvsd6zirJv+dUlcxYcWFpxtYgQciZODoyIYaqfKjodUyYuUlr0yZJJvEsGZEZyimCGLhz+MkA=,iv:sA3QcVzYM/Hf2r0dj2KihGT20tGnG8B09XaYc46pNm8=,tag:+xbOPd3XEfgS4nN0ZNNtNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
