apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceAccount.yaml
  - role.yaml
  - config.yaml

commonLabels:
  app.kubernetes.io/name: homepage
  app.kubernetes.io/part-of: homepage
