apiVersion: v1
data:
    NEWT_ID: ENC[AES256_GCM,data:ycLWno5kXVt6pJCJ6pxER8uIh7c=,iv:LLhy5JGlKHmrQUkTZth9uBGmHrhgE3YPUTfsalenEsM=,tag:U0tt3YaNgBW4bwZuOhizww==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:fCzy6/13qg5mKoxxET7dJZTH9RX+RqxD6vBRjI0IK9roNKGLIRYkRWjFRHQ7TksWEYtEUp8ANt3b6ce8p49mJQ==,iv:ThmLEwP3DHphKLk+iiVUxIs95pZnl9vC+4PHLxv+BLU=,tag:pPWFRVvS/BfBzdEKeOLt1A==,type:str]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:VeN1j2P97MpubhL250xTanYgh5n8bu2uNjhBKROQ0QTu2VOy+QJ3eAhWP4o=,iv:YAN7gxXVk+Ts9WwFCp85+y4sPBrbClAl13ErazwjBJU=,tag:uKrF20sTljJ1ZM4wwzzFLQ==,type:str]
kind: Secret
metadata:
    name: newt-main-tunnel-auth
    namespace: newt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZVd4WFIxVktyYUR5dlZy
            dFBPblZxdXJyckYwbTF1UFdQczFRMlNRWkJvCmZoK0dCSVA0RE51U3MyZDBqb0l1
            NnpTOEtHMWgvYzhEQnpqRWZ6eXhQR1UKLS0tIGVNcmxmZWU5eUIrK1c0bUdDbjlD
            YloxcS9Udm5JOUtmb0VOYXJmZ0FrQlEKecyTqInJDCG6JLkxi7FQ7bU5nfw0wU1F
            TXdnDYjDKka/if6SWXMJyLWuHvX/94wjNEcN4QTolDHszfQ7TJwpUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSmFZMEFUYm1mQXI1dkUy
            di81Tmxjek9ielpXZUhWcW9aZng4cDlBTlQwClA2eXB3cXd2cGFPSGNEWU1GMGZO
            R1dIWnVDSVFHSkpVSVZzTkFVOFFZYmMKLS0tIGRaaDFRTTBMNkNkRE9nTlNWMUYv
            eW44ODMvLytsM0JWN2I4QkNLWUU2cncK5JpqTGTg9mnmRFR2RJUpa9tr0LM05l/4
            tTadlWqm4XFMkOmzuND2hZbZAa29p4krU7pIjB0yFRbSYaSRoB8x/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZW9KSUJRRzRhWm1MVmNy
            ME94YUtJemxQY2FHbGt0NXB6TVRkb2lvdXhjClNxcFdlM1crNXBFMzFIM045a0dp
            bWlObEJkaG9pQWlVZDBhbnJmRnNrcHMKLS0tIHZhanRTdks5WWZNbWQydVp6cE9D
            bXNBdWsyKzFmVGVsWi9DVmxyRVh2bHcKxG4CbLCRqPxshrFMYUTw2VpnqIr/MVLA
            tutl+JW2SW/OmyCvpkdKE6cyz5GaejZigWbq3P1obeGbG4vtiCOcpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRHJPQ3h1dlQxaStiWW4v
            WUxUNkZVRi9YeW0zR3ROQnYxUExIZFl0TUZJCkUyUXh4SjR3KzNpTm1jYUh4d1ZK
            NW9DVjR1SWxqSWhrT3FReGZWRTYrSlEKLS0tIHFRVmFtU01UUzRiSlZWOUdMcEk0
            dUYzMlNCRGMzTGxSWWQxRTQwRFpOOGcKgmIqIhNwXmtLJIqmoIbM/SRPOIJUsie1
            kkayHRrR0n3R6L+xH/WwZoxNTJEpxMdf6IBHOyJadJK4O0GECmY8ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T10:08:29Z"
    mac: ENC[AES256_GCM,data:xcE0pKC31HKqjGc1pjmhIIM3UId8pqby8mL/aazOHLRWGaiRBfMKTMfO6yoBOQ6v9ETr55J7G5aF4eTAYY5b8Tf9yoEOADzIkdJpmdOaOycm6rgyUUN5GR0qkySyeE5UJ0vYsbU2VYlevNbyS7bonCCKXkF8rlkypkk8qAxdZAA=,iv:z70S6/FyWwd7nFWGb6lsp7qgH0VoDwLpLIJgK3d5daY=,tag:Yjab8hUunRWRjtha5ziKrg==,type:str]
    version: 3.13.2
