# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-database-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:FhBJ4kHiN2lE8aWmdLQ=,iv:Xd9KgpSZsb6vQf3ax8hQQkr078C/RVDlUDY+9/lPpxM=,tag:pOc+L/hYCg6BbXMP+xiwsw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNHVaT1RTZmJ2UmszV1lZ
            SWMrUWRZbEhyN29ScXJUTGNmaDJqMmNQWmxNCmhXS3ZZQW9CcnpqQndkQ2lxQzY2
            c0JJUU5pSElCN2xhcitpMyt3ZWFJNjQKLS0tIDFKdjNxYlNQM0lncVNvUUFyYzdR
            RHIvNWlFcjJqa2NxSjA5dnFwWVE3YW8K6J/8MxGYLHz7hjfZqs/CsyxdgrjAavUm
            Ydj78VNx0P05vY0/1KRMUEfuhi8gbPEOxZx4+RoY423y16jjYqZWyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Mkd5OXhWellDNWI0Nkt3
            eWlHV3ZkaUtUWE9sZUVIbnYveDVmRkpGamdFCjFhWktibHB1ajJtUkNqL3FTRWw4
            eWtJRXQwM0ZvdlQ0bHZ1S3JYamRWdjgKLS0tIE0vamh2RnBUWVJGbHVJOWVaN3Vu
            NzJUeVltSGJLa1JuVHZ1bUsxNWI5dGsKwDN2hI4SJ3GwUbN+aUB/v+pmmmbWRLDu
            fRxit4FI8f2+BFiNWGODQZRR/lg92se/4ZEoLgc15/TmWTf5JyJ6gQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6blFlank0REN5d1hHWlFV
            a0M3cjlCdFNCNkRZK1VaUytaUVdVRThSVHpJCjdpTDUwb0xrN1h4SzJPbWZDOVBr
            c0dqRUdMb1dDbVdKMGtJV3NkLzhNZmMKLS0tIFVwR25jMFQxbm8xTXJKNVE3Rlhn
            Zk5MME0rdXAyOUFOY2Q0RXRGN3Q4czQKO2/JfkCNqqjPGfjnXxg+NrnO4cYbRzpb
            z0J7KbXY6/XKShmMZLBKco/3fD+bySZcnkUxsRsfuQdFQFVvDHrdjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RVU0aVh2a0NBN2JIL3E0
            MDBFeU9mTk5lV00vMjIxZDJSYTlFM3NRa1hBClhxTW8zTHVoQ2pjZU90QTZYbDR6
            aE01ZlkzSklsZXhndnB0eDVIV0NnMVkKLS0tIDFpNVlrRmpKb0JYRVQzSHhHSWdw
            UkxTc2krUEtWdlJJK3JhUzVFaXpvajQK4FNoZgDkqq4b/qlgBILAcc3AeUPlbo6Y
            OsgYcWtHNBRzRsLTZqO0T4G6aqjRjaADLxxM9l7DdvbfY62t4rY03g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T11:03:22Z"
    mac: ENC[AES256_GCM,data:m3P1a9QUmIXOAhSSJXqSr/6Ctr/kMuxIeZ727BRZsg2zo/Doar7diotJaS2Ktl8OkNgTn3fqL+1eEa5n93ApJGwb4ylI8HJjOyG7PkFhQYEzEBENsV1xOra8O7UWc6t6M0lmcTjTF7VjYDnwCZa8qc8P6zgkZuK4tn5aCIxkw40=,iv:ZstzD9PMpquLF5Dltt0Z52+fWj1jXLDrtWpQIxv9qb0=,tag:ex+R0LpPqRSbaJJo95FuyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
