apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyseerr

bases:
  - ../../../../../apps/jellyseerr

resources:
  - namespace.yaml
  - database-secret.yaml
  - settings-secret.yaml 

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: jellyseerr
    patch: |-
      - op: replace
        path: /spec/values/ingress/main/enabled
        value: true
      - op: add
        path: /spec/values/ingress/main/hosts
        value:
          - host: jellyseerr.yohanzbinden.ch
            paths:
              - path: /
                pathType: Prefix
      - op: replace
        path: /spec/values/persistence/settings/enabled
        value: false
      # - op: replace
      #   path: /spec/values/persistence/settings/name
      #   value: jellyseerr-settings
      - op: add
        path: /spec/values/controllers/main/containers/main/env
        value:
          DB_TYPE: postgres
          DB_HOST: main-cluster-rw.cnpg-system.svc.cluster.local
          DB_USER: jellyseerr
          DB_PASS:
            valueFrom:
              secretKeyRef:
                name: jellyseerr-database-secret
                key: password
          DB_NAME: jellyseerr



commonLabels:
  app.kubernetes.io/name: jellyseerr
  app.kubernetes.io/part-of: jellyseerr
