apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../apps/jellyseerr

patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmChart
      name: jellyseerr
    patch: |-
      - op: add
        path: /spec/valuesFiles/-
        value: clusters/ocr1/overlays/apps/jellyseerr/values.yaml

