apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../apps/jellyseerr

# Override jellyseerr ingress host
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: jellyseerr
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: jellyseerr.yohanzbinden.ch
