apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - release.yaml

generatorOptions:
  disableNameSuffixHash: true

# ConfigMap for common configuration values
configMapGenerator:
  - name: vaultwarden-config
    literals:
      - DOMAIN=vault.example.com
      - SIGNUPS_ALLOWED=false
      # SIGNUPS_DOMAINS_WHITELIST: example.com, example.net, example.org
      - ENABLE_WEBSOCKET=true

      - ROCKET_IP_HEADER=CF-Connecting-IP # header used to get the IP Address
      - HTTP_REQUEST_BLOCK_NON_GLOBAL_IPS=true # Blocks request for favicons on internal ips.

secretGenerator:
  - name: vaultwarden-secrets
    literals:
      - ADMIN_TOKEN=super-secret-token
      #-DATABASE_URL=""
      # SMTP
      - SMTP_HOST=smtp.example.com
      - SMTP_FROM=vaultwarden@domain.tld
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=myusername
      - SMTP_PASSWORD=MyPassw0rd
      # Push notifications
      - PUSH_ENABLED=false
      - PUSH_INSTALLATION_ID=""
      - PUSH_INSTALLATION_KEY=""
      # SSO
      - SSO_ENABLED=false
      - SSO_ONLY=false # Disable email+Master password authentification
      - SSO_SIGNUPS_MATCH_EMAIL=true # Match user if a user with a matching email already exists.
      - SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION=false # Allow unknown email verfication status. Allowing potential account takeover !
      - SSO_AUTHORITY="" # OpenID Connect discovery endpoint without the `/.well-known/openid-configuration`
      - SSO_SCOPES="profile email" # Override scopes
      - SSO_AUTHORIZE_EXTRA_PARAMS="" # Allow to add extra parameter to the authorize redirection.
      - SSO_PKCE=true # Activate PKCE for Auth Code flow
      - SSO_AUDIENCE_TRUSTED="" # Regex to trust additional audience for the IdToken
      - SSO_CLIENT_ID="" # Client Id
      - SSO_CLIENT_SECRET="" # Client Secret
      - SSO_MASTER_PASSWORD_POLICY="" # Optional Master password policy
      - SSO_AUTH_ONLY_NOT_SESSION=false # Enable to use SSO only for authentication not session lifecycle
      - SSO_CLIENT_CACHE_EXPIRATION=0 # Cache calls to the discovery endpoint (seconds, 0 to disable)
      - SSO_DEBUG_TOKENS=false #  Log all tokens for easier debugging (default false, LOG_LEVEL=debug or LOG_LEVEL=info,vaultwarden::sso=debug need to be set)
      # Yubico OTP authentication
      #- YUBICO_CLIENT_ID=12345
      #- YUBICO_SECRET_KEY=ABCDEABCDEABCDABCDE=
