apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/vault-deployment.yaml
  - services/vaultwarden-service.yaml
  - ingresses/vaultwarden-ingress.yaml

# ConfigMap for common configuration values
configMapGenerator:
  - name: vaultwarden-config
    literals:
      - SIGNUPS_ALLOWED=false
      - ROCKET_IPHEADER=CF-Connecting-IP
