apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vikunja

bases:
  - ../../../../../apps/vikunja/

resources:
  - namespace.yaml
  - secrets/db-secret.yaml

# Patch HelmChart to include overlay values
patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmChart
      name: vikunja
    patch: |-
      - op: add
        path: /spec/valuesFiles/-
        value: values.yaml

commonLabels:
  app.kubernetes.io/name: vikunja
  app.kubernetes.io/part-of: vikunja
