vikunja:
  configMaps:
    config:
      enabled: true
      data:
        config.yml: |
          service:
            enableregistration: false
            publicurl: "https://tasks.yohanzbinden.ch"
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteMany
      size: 3Gi
      storageClass: longhorn

  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: tasks.yohanzbinden.ch
          paths:
            - path: /
  env:
    VIKUNJA_DATABASE_TYPE: postgres
    VIKUNJA_DATABASE_USER: vikunja
    VIKUNJA_DATABASE_NAME: vikunja
    VIKUNJA_DATABASE_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: vikunja-db-secret
          key: password
    VIKUNJA_DATABASE_HOST: main-cluster-rw.cnpg-system.svc.cluster.local
