apiVersion: v1
kind: Secret
metadata:
    name: main-cluster-backup-user-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:2QEPh9BpUHsVG9tlM8z3LOM0aboP,iv:6pZ+ZQ2bcfF9gmYMxmAL5SkIYDWP9QVACsuc3XjwtsI=,tag:aGsgX7Eey3+2Xlv9R89gzw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR3pJMzlUN05LNTlqeXJ2
            WWFrUjE4MnBFZDVuWTFQejA2TEZwUUt2bUQwCnFqblF2YnVVVGJJSFJyZG1LY0VK
            MGtzNy9RaTFYeGhSLzZxMmhvYTZldmsKLS0tIFNOQTAxY2h2R0V3bEU2ckVLNU1F
            K0JFMUtDaTVxUEFlR3dxYUVxcWZXZHMKrnzDDgwYtD0ozOqCA6o6TEw/ZGv6r5Fr
            pqv3YfTH0/TR70gSuipnuYV7J2HAQwQfHYBGOeXUVGJ63ymeWZkTag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERTJJbzRRc3dQdHhOaCtS
            RStyWFVobW1TMGVqRmM3YnZaQXZubkVvSEhFCktrWVhWV0E1SWx3clZqV1BzYjA5
            OFBUUlp4OGsvcU95bE9wdU5GS0RVTDQKLS0tIFlWKzI4eXBtUFJJSUtCZDBOSkpt
            Y0pVbVF3TkFOT2VGYUgza0lKY2taVFkKVx1H1Ut0RUrvHiuGuW2y4jFdncWiGoUZ
            cBjmDj+plc2we8BTiYtnCTR+kdO/iUE/fKGyaiIGeXL5G51N+SFSQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTkhYRmdNRGhLOHhoWkt4
            K2pQcEZ1NlNYZHVjNFNzSWJPbmJDWm9aaDBvCjg5d0ZtQ3hyblgzcWwzQU43OUdp
            MHRwYzlzbjIrdGVSVWo5ckJrSkZEZWMKLS0tIDVkMklxSG9kQnRZMy9sMGZ5dFUz
            MlhlRHdXR1lHMVNxSmVRN21VbGIxNlUK004NF7yI1s/cu968evFgorXwRAFXVl0Y
            J3/zw082udUI7XTI/F30BLbzvZGn85CbA24rUCYt+dw/WWbrdcacig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRDhKYVdwTk1GbmQ4QU9M
            L244WWpkVEQ5VytxeUdlaUJMVUxGV1Z5cENnCkZKS2xyaStXVlBJL1dJMmpiWFgy
            cXY4WDZnb09Rd0haMjhTa1FWWm9UUGcKLS0tIEkya3J0M1MzTXlpelJMSnFOM3Q0
            R21wQ1RKNHVwT1FFM3hSUWRodmlJUVEKIBF2XcbyOWIcdYyocLmX3g3wckKhZbpE
            kEGINkqYBjUyOpMSjdHtytaeUVqeVTO3L8hV4peCOsOOWAnGCdkNNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T07:38:01Z"
    mac: ENC[AES256_GCM,data:lkbK+J5YIkNeNWRG3IbdmCXI3MfwtgKmXn9Ka2ButlOBqYWaMNs9UBa9dqBk2qAVdVnhHvLOOIAOiYmdjPUn1NPsvpozfEdFpD7qs8ygbIOUEq4P1Ezc3nwNwTWYEVXRwM+wS64A+u+y01JWXwu8BXPnKCL8vTG+A6Ba8hrqT9o=,iv:Oqnf2R2jHXXLbK484/Ur5d7Q6vw/CEf2PsxxtMScmKc=,tag:wCaBW06rbxO84iaoQnN2zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
