apiVersion: v1
kind: Secret
metadata:
    name: main-cluster-backup-user-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dY1bfO8R/MOXcy8=,iv:Mvvui31gogffxc/oyDQFrsZYRsJCseFzzakwd+ST8/c=,tag:X9eNkV8PifyjkaiC+k6AOQ==,type:str]
    password: ENC[AES256_GCM,data:xYjfjHjJ+No8lOHuiTv8rUjOqE8+X4BNyj0M7IJxfGQQyKgOMdK3aywtlI6IZWstxLCWWXsYf81lNEy2ur4T+WidQJntlpwGUm0pTyI8mqt0xp+N2IETQx0V8e4B1olgmxuygPPiwJi3S4/uaioCCL8hDyCa0PUs2k2WxwYmR6zfIAs49A==,iv:fWdePXeGv1Li8lOZ9KvXMoTKwCnDhlQV66hMV3wQvuw=,tag:46fuMptktgHDvXgO+5x9xQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR3pJMzlUN05LNTlqeXJ2
            WWFrUjE4MnBFZDVuWTFQejA2TEZwUUt2bUQwCnFqblF2YnVVVGJJSFJyZG1LY0VK
            MGtzNy9RaTFYeGhSLzZxMmhvYTZldmsKLS0tIFNOQTAxY2h2R0V3bEU2ckVLNU1F
            K0JFMUtDaTVxUEFlR3dxYUVxcWZXZHMKrnzDDgwYtD0ozOqCA6o6TEw/ZGv6r5Fr
            pqv3YfTH0/TR70gSuipnuYV7J2HAQwQfHYBGOeXUVGJ63ymeWZkTag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERTJJbzRRc3dQdHhOaCtS
            RStyWFVobW1TMGVqRmM3YnZaQXZubkVvSEhFCktrWVhWV0E1SWx3clZqV1BzYjA5
            OFBUUlp4OGsvcU95bE9wdU5GS0RVTDQKLS0tIFlWKzI4eXBtUFJJSUtCZDBOSkpt
            Y0pVbVF3TkFOT2VGYUgza0lKY2taVFkKVx1H1Ut0RUrvHiuGuW2y4jFdncWiGoUZ
            cBjmDj+plc2we8BTiYtnCTR+kdO/iUE/fKGyaiIGeXL5G51N+SFSQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTkhYRmdNRGhLOHhoWkt4
            K2pQcEZ1NlNYZHVjNFNzSWJPbmJDWm9aaDBvCjg5d0ZtQ3hyblgzcWwzQU43OUdp
            MHRwYzlzbjIrdGVSVWo5ckJrSkZEZWMKLS0tIDVkMklxSG9kQnRZMy9sMGZ5dFUz
            MlhlRHdXR1lHMVNxSmVRN21VbGIxNlUK004NF7yI1s/cu968evFgorXwRAFXVl0Y
            J3/zw082udUI7XTI/F30BLbzvZGn85CbA24rUCYt+dw/WWbrdcacig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRDhKYVdwTk1GbmQ4QU9M
            L244WWpkVEQ5VytxeUdlaUJMVUxGV1Z5cENnCkZKS2xyaStXVlBJL1dJMmpiWFgy
            cXY4WDZnb09Rd0haMjhTa1FWWm9UUGcKLS0tIEkya3J0M1MzTXlpelJMSnFOM3Q0
            R21wQ1RKNHVwT1FFM3hSUWRodmlJUVEKIBF2XcbyOWIcdYyocLmX3g3wckKhZbpE
            kEGINkqYBjUyOpMSjdHtytaeUVqeVTO3L8hV4peCOsOOWAnGCdkNNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T07:57:07Z"
    mac: ENC[AES256_GCM,data:sRcXMi/CLdz9QEK0TkZmsdwnnV3mcy8WMFarFP0/buDOWKxhoSZj/MR6acqgrqCQq4NsjwWgad67CtvHOf5omDvVLxzRYH/Oy2F7q6gj3txPl6m2nLzC7kY1QfpWzw3uwgGrOO1oy0QHBIrK1w8EQPgjibnGm/2pHyN0W/gW31w=,iv:9IXEEF8OqkZszjgTzeC21TZlB1CDOiNSwtIXfCWT18E=,tag:mFpfXW1tw7LauUZ3lR7wAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
