apiVersion: v1
kind: Secret
metadata:
    name: main-cluster-jellyseerr-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qm6wCzlh/KnRAw==,iv:7O5d93hIys6dyuEF/7xz/lQpeyreWg5qzVx6rxvJbRc=,tag:eRxmnpwSZ2G8e4Q++oq/3g==,type:str]
    password: ENC[AES256_GCM,data:41ycLyGUKiQBnRaZZcs=,iv:TVzB3Uv4+xoTFcSBydMxqP6TsXikQpTH+QsMgsQAs7o=,tag:gGjXwyx3AA2adtR6y+kUNw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQVVReEp6SUppTElwMlFG
            RUlUaVJkcVBVckJmaFNwaXVhaWN6RHZvRm44CllRRVdtNStNT1dnWUFNN2xCQTYz
            NmxSOUsySERYWkJqT05hbE5QNFl5R3cKLS0tIFJMM2MvaUNXOGxWR21PN0t2azly
            K3lhb0FYZFB3V0drM0d0djVvb3pSMU0KFU6Eg2y6SB148zcZLqO4DZh/X0l6rFi2
            MUq5nEZiJIKp2qUAUcV7CAzXHmLOSGV5P4mfG+hpP/lvGx9KBRnRqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneitzWDNJRnpLdTh5dXhY
            T0VvaE4yYkRVNkFtWkE3SitCdG5GTCtVbDBZCjlLdXRwYW53VTdBTVNDV1hKa3Vi
            Zllnam1ZQmJ6a1NSRS9nU0dkN1A0WGMKLS0tIGYwNDI0bzZocVRnL3UweVplK3dv
            Nm9yRTgvTm85ZlZFLzJVNkpJQUhNc28Kn0RXy906HrN3UvjrR7/GYHxFKXFC2Dt3
            4K470LmlQanSeviU6ZalGKpM1PA9dWTxYhsAFskOBkA32OaLJr7oXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcCtJcVBFRkpsd21McE5P
            REtCN0FBQlA1K3REY21ZRXJMZ1dLb2tWZkVNCkM4WGNIWnFLYmFUYnkyYUpnWFNU
            U1lmOWRHaTV0R1M3bWRBUWJaZU5rcFkKLS0tIGQwVWM0eEhNdmdUVnV3MDFvTGcx
            ZnZqQkFqTVZPRGFDY3doN0dscTByTDAKlJyhWNATIZkMsIpJpAAdogu4IdSz21bK
            Dw73nvxm1GkJpElliJLFLB5uFiZDD5tBWg/bivXOXi+ZIm7hjBAihA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcVJKOGR1YzBFVU9pQkpM
            WnpaQzJ5cW5EellTTFd0bmJYNXFDUVJ4RjAwCmoyZk92OFlaY3dUdmNEWXZhMUdt
            d1JOVDd4NU9SN2VMNnRlNDhIUFVJZ00KLS0tIGZINStsVklKYkpxSWVHN0NhMEVY
            UnZKMXRxVWZsRUIxNHBxTXQySU0wVTAKQoqdH452kuRGKpGMrEUxVSxGd0mTn3XT
            G8Cs4LJTs0abwO+E/GPoKX0usNGNMP0OeXzEc8EhHQ+S7+drDVN7bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T10:27:52Z"
    mac: ENC[AES256_GCM,data:HeCQYVHgLXkBOwW9Qy6N+Koam3qjvgKJtKmPVyYnUJ9UbpIRBznEU6NE/aAc/DmkyjxlSCIzZePhdiKP8c3oyhCUkzsErqFL7ZhIUCIYRljZQRvkNqCr8ZeRHIntEB8pAWje5G2gbPZk/iF5Exdx+dfBs4ggcVj0JGwybBmQX4o=,iv:y+LCSKZtB/OpSThu02QO1oreZ9c+xafgc46pn4IHlhg=,tag:Wqg6vMAOzq//FvuSxqBReg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
