apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: main-cluster-pollenzo-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:af9A8qkroSw=,iv:iojItsKQ6RT86juW7aqQLVkJKbiF2c3lozf+1h0H+Xk=,tag:TbHdvlRlZQRFHf5Tznq5rA==,type:str]
    password: ENC[AES256_GCM,data:OT/ncjTe1P/UGOYIJq+iKH2PcYI=,iv:uPeNkplrsh9vkUtZ1lE21L1OBYDPKw2ofqiUe3EnerU=,tag:vWEVSqcY4VO5nY9wj4st8w==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOHZSczhFWUVycllxSERR
            K2RMT205Z1B3YzhOZFhjdkdkZGlBV3Q2YzBJClovbkFFRENaeFBDM2tkTFVVbjBR
            d1VZZGdScXN6VWlMMjZ0NVNxM0VxbmcKLS0tIHUyUHpDZ0RkR3NZTHE4STBPci8w
            dkdyeUp5bkdva1VsNk1oTzViNG1iWGsK+sSbnG7pdYUcckWZEtvJR1JgZVd61JCb
            1hoPIcM0MOCivPXXmTnVoFmvqQGVMQnP2YGY8uOmH+CLp574ekiTZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVUZpaDZSYzdHMG0zY09T
            N3RNdDg3UjA0UDQrL0R4QWZ2eG5nS0ZUT2pnCm1RNkp5WGxFc29vMndiTVdpbHF1
            aXpndzROWGVWeHFuQy9VeklmNUttZmcKLS0tIFkvTUx1MU9lYzgzL2FxUzRhSW1t
            ZVVoU3pDUjBjazVtVWN0djFXVGlla1kKZDiHQXn26To0ne+0MiR0z7SCcRnREmBY
            k0TnEhri2MKyVA+efBaRUjR4eGznBrmZ120XYS+LxW3IqkZ5vaVXtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeGk4eGJGYk4zcnBNOFJx
            c2N5M0lqRTlRamRwZjFLcS9ZSXNqTk5lamg0CnRsV1pYdHlpOVlRNmtURWFWNVk4
            Y3Zna250dlZzYnhJT3JnV0daZGl5WVkKLS0tIE5hZlJkRGVGZEZoU1gyNUpkVWNh
            NTNWN2NIeENrNHFzZlNlZVF1Vi9iQUUK3avkBM74GJCrEcJDTlICKFWoW/aVEJ4r
            S78o8C+lOqv+LD3dZMXv8a2l4rbx5nlA/4eXhZHZFl7Mv211ePQlzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVnhwQmNTK2cxYjB4L0ho
            UzdsMm1sSGpqekpwVmRtMHQyQjRrSXlWbHpFCk4yMm93aWtlbHF5dmp3SUVIWE00
            cGJ0SWp2RzhvL2FjVEE4SVFpNDAyUGMKLS0tIEtOb2s2RUF4QytxcFQwbTMrcXFr
            dnoyR3Z5RXM3UzZQK0NBMDhVRFprcmcKW4lx08VSEL4I5MOwoHhvyh34xzhDiW2g
            dIhlv78/bjghntt4E4xROx/F7fXKIlQhSeei5tRhPd8HkkOeD6NqfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T13:36:28Z"
    mac: ENC[AES256_GCM,data:21TrQSCwzZ5lzlXmZhelNXWJQOvHwtF2bA2JuFZ26XHzE+yMbwS5Qls2wRGFRcXgYJOUmtNAvm5ETbYvdtSruGNDSaQf2RyOSjuzu/1YQKLcY8xhhRwSKcOH4r6I1Vvt144UbfAYBG/cc+K4uE7tjtOn/XGxa1yAtna35n0SbkE=,iv:7XcJh/nbi/Ca37G65zw//zko8YXAHAXw36W30dzCVoI=,tag:Dtk+LVP5Gej2bX68171hUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
