apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: main-cluster-supersync-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:LeqI2suVopva,iv:QlETcd0tCL+0K3Bb6iC4FTAJ48CAAdoPJvqsPwNlOII=,tag:d/RqzWmIuNyPJydK9fATTw==,type:str]
    password: ENC[AES256_GCM,data:3SOs4aejTofOKJ0XqeQ=,iv:ucD1NcYRAJSXdGSXuKpb/VBiCQtuOZ/3INySAeLXeVo=,tag:t9cUOoYGYRDRUBG4JJrFuQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKODM5Y1FXWklwUzFlSk54
            ekM2MlMvM0psZXZnL2t6U0xtMk5Bb2l5QWlnCitTTHMyUGtOQnhWYnFWNy9mSTBy
            MFR6WENqZStHdjl6eGp1RncxRVJhMm8KLS0tIEI4N1dSMUNESUhHUGM1NVdKSHR6
            c0pXczBuQ0VXZ0tUNW8xbnZiYXZaT28KfiajCgSwfW0ggaliQsyGJACboQaKvNwK
            5K8y3+8a/D6GdXG8ug+L0AL4ygEBG9wJyKNakPOAI+qamlhpgw/qxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQWxEYStqRkg1aldrK1JV
            WGxMViszeFZ3enFFcXNNSHZSZ3MzczRjSkhjCmp0VWd0RXdqTmVkVFArMHdmRHJM
            YS84d2RJeEJERW1nUUZXRDhIVGExcFEKLS0tICtXaWUvdi9VNFNmZXlkcHZ5b2Rl
            dm11eXJzTm5TbjZCb0w4UFJnN0RNcEEKB9jfCKrEbJUDUXiqVuEJsdjX6LV/53Y+
            fIYRsS+0VsHq2QgKv5waCTPF7/f6P/aabJOkcRLiPuGQ0o2em5KtXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSFdsYXNHWkhiclJyTmlB
            WVFud0tkcWoyTUxMQmdFYUZ3V0x4d0dnNG5FCkx4ZDJMUjBtUjNLRndKQXVraG1C
            VTBZTWRDck41ejVESlQ2eUNQakdIVXcKLS0tIE1YY0hNWWNIdmhTNEpsU0lmREFk
            S3hTR2tPSHczWXRsVnhPUDRVZXVtWjQKpqqYsAjxlFXcloUlRDWTDMyMO2YXIkBs
            7VLVjZpxeJLC7z2gJ/bs7mqB/REHfN7q/hP+K68pGSu1fN/eaFHeuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVGJVYU5YV0xJSzJtZWtt
            RkdJbDBSdG01cXA3MW5KT2tlUHNHbno2WGtrCjRUOHZqSUxxV0cwcmtyc3BqTEtC
            ZUMwL1RUSHB0RFZaL3JmUnRPeFA3TFEKLS0tIFlRcWJMZ2UvNmo5OU1nT1JQMFYx
            dEU3OUVIblBJNnFoTmx3UzhxQnZiMlkKVZe+/YCaOAGGfbQs+quEIUbz8j5UZHNH
            dmt5sZ+CfGogLZGwIjhIOPiHI9pQXVMHb9IWagnBOrf3mk+64Wbkug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T09:31:38Z"
    mac: ENC[AES256_GCM,data:oTCsHO3V5Y61PCIdJSxdoX4X+EDqB+xQWzFmdKB/W1WGCJR5Uj1uoXPe1WkD6E/E5gticoan0lLKadoE41BZTDTQTTO3zwuaNHlCmUWNkO3Nw8URB8yjOp3+LrJw3XiIuiByazhEuC1uKlOe//LSOdryZlQi+0jkjVtlD4327VA=,iv:zuNhR3zEGaW+Z4bGvqBym3iX+l6SFF7Qtq/qjbYfXew=,tag:+QccU34IkCrlzKYQuk9afw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
