kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: main-cluster-vaultwarden-secret
    labels:
        cnpg.io/reload: "true"
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:QeGyxYhgIJJoL2Q=,iv:TDwemjOLOn9IjuJt4o6URJamFYtVbqkvdrN+t6Llxw8=,tag:9zo4a7xQ+5Mg5hAQMvXROw==,type:str]
    password: ENC[AES256_GCM,data:va2J7DijI1U/tiCQo410d82dv0A+wWA1uPkGwEzuUpxyS43Az53Po9Ew0fXk+MNid0vzS0gk5QMFCwYV8TpN6uuzwx+bxSBj9WFHnayrEA+Rea3gGJ1kwY8X2j3pLLcne/1PPMW+YIidPjIlQ/zTjaKaL8SzNTJxLqqzTQKNwui0RI2FUw==,iv:F747ckyp3JskoClq8jFQH4aTPxrGM+oS94pPRyJA0tg=,tag:7nxqFgML+ftv68zPlAHeTw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVDdlWmtucHdjUzdhc044
            UUVmSjVnWkRLTGtFZ0dydGEwUWlxU2dPNENzCldLOTlpOFd6YmE4RkZhZFE3dmxJ
            cFJhbjhPN3FmKzNEYldoaDR3ODNFbUUKLS0tIGJZMUViWG9BTFRwVEZXMWd6SDcv
            VVVETlJ2cm51ZHBPc1V1NW9UNXdDbnMKKq3BUjiU2rs9tpxJ1IVBkhss6whnIMLW
            S6mwH9Juyzyi47H5HrhzeeV3qhPHicY1DEeC4FBxSkFW6MzfBxOfJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ymp6N003K2FCV2xGbTJZ
            eVZyenBqOWV0RkI2N2MwaHZxYU0ybGFJeXp3CkVrSjd1YittNXc5citXOU1UbktU
            QmFNSUxlUDZWR3YwZDBuNk1tQ1pQZnMKLS0tIFgxNFJhTCtFU3g2a096V01xT1Vo
            YlB0U3F4b3JPRm9LZjQwSnpPZFlkazQKzcQ1SJy7awjzfpuqQ6dawgcg5qS/IyHv
            DzAtkmUxkC4nzJ36V/8QXoElv1uppLHxDGnq9WIgf8MWJ4iq5ja1KA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ0h1cXgxVk8rWEJpT2Vu
            SFVJcEVZSmd0eWZKc1RYNU1FRGFxNjRRSXdrCkFQNEJ4WjZjejJHTERzVEVDTjRp
            UkVFOG12QnRYdEM3WndDallkYVdXNm8KLS0tIHFpWUdSSm5VT0JpaTFqWVRpZnV1
            LzcvSVBDUmliREtEZi93c3Bjejh3ekkKXMYGrSacuW0EchRd7753GOIwwivemFlg
            mHawn6Rp2vaTvj/L5Bejj6GTxGdSneMQk3gb89kz6LuJZJI2vP5qMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReG1CY3hkcE9vT1lkQnY4
            Nmk2akRuOWpGYkx0d2kxangrT3MwaTRFTGc0Ckd3OUR3RlVzWkNmbWdWSFFyTURh
            MW9id1lrTEF5L2pqOE5QNit2MCttNU0KLS0tIFFmeExhT2VnT2syU2tLWWtmZ3JN
            MVBvMWJ0T3BLSElHTHNJNkl3QkY3TncKi1HS3tDGlbjhSMZ6ctNJwCAf1F1lP4dA
            DKuwk5hsa2A5r1gqjQeXJ9D2V8v+SaZUfKTXCZyrmvg18L1cvQ35WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:20:52Z"
    mac: ENC[AES256_GCM,data:PU41l8IZtnsxJMB5IxgWvbJPoTS/kGed6rYr3MM/mr5Vef0j3xUbYMNVfgIp2XgUjQiyh4zt/xMU0DmF6UNT9kL730ott8DML+seaSlYk5D1xXJz76t4YXeW9pE7jtdLIKfG/GOqOEOe3YVKyPZYFUt7YXxeZ2Aa8W8lhzVOnPI=,iv:nPlR76FO3kRSxp3070Mrsg2Qa0MN5uS6mOk7QKuJOK0=,tag:SUawrq4uckBSSUX1mJoNtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
