kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: main-cluster-vikunja-secret
    labels:
        cnpg.io/reload: "true"
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:3ZFhYvvu7w==,iv:QgYLtScbyrjMfHZDT3h1Mc0e1rgXQDcQTxOzNxvSC/I=,tag:uCtj04odRUsiTAOrRwP6Gg==,type:str]
    password: ENC[AES256_GCM,data:C+lBQ8YAAKv0nlppIvTKBrpAfANEOyA00I4iEDkJQ7cJ7irSbadNvcMywQ5uP6XtGFgqwoelX7th6tO4h6MPLxMA46c1+xTOOoFWeD+Va7c88Zttfy1KFHL2umq39CuCbOS6UbeiSEWa4x6jYB+oJN8v7Q8FYruFyhG7am0zk+sZBKx2sA==,iv:il2PJsC9lmAfB9QwwPOEIXRHMjbkHGTYrwhX0dzSIzQ=,tag:Du0rgr1p/jrrnIKhVHldIw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK2psaHphbEI2aTZEdHZB
            UkpiOW9ucTlPTHpEY2oyb3Z0azhLNVRpTVI0CmdUODJUVFVzUFcwN3FXUzE2OTFV
            ZWFmeTVndm9ZVG9GSXgvdHpKbzVyMkUKLS0tIFdBSXZSdnFvS21objNuUzZIcXF1
            NTVZaHRMTFR1cjZiM1l4MDB5THcra28KW7dcKH9B5k4jHOoXFkBgrAog1K1mdo37
            RG9PW3r5cBYyN+oIM+E+bgVz2QUYLeCGHZ7VUIEW6ZXJ27Pc/1O0og==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScUpBd2d0N2QzR015TnNn
            cU9wdXpocUR2UXkvWThoQlpuZW1ZemxHNzJBCjFsMjVTTWlzcTFYbHlTQ1RINzZu
            eFhIaXFreitROU93cFdoQ0tuQWZVQ1kKLS0tIG1nak5SaFJhRDk4RnhQTXNsd3Bh
            WEhaRFNKTGtGaTFUK1A1SndNbStiKzQKnOVC2bzyPmsJlsQfqYNQc8FeaEnHxizo
            VtnN6zRmSQJui50S6HrsjeupHigA+wMvpHFqqjOdg1kvfJ0e+tY/Mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QnAzNFJDWmlaMVQxbTMr
            YXAvYVRtTC9aVzVYM1R6OGRONnJ5M096QjBnCjZ4Mi9WcVoyay84YUtBbFFFblVU
            azlBVXhVcGNHSDVGeWdidTR2aFEycVkKLS0tIHNiQkxTWnNJT2JNRGpQbzlnMG5o
            NTZDRTQwN0pzRzZMSXJLZGZkQVZUWVEKjYSsAvcecQuvd9m7kg0SODLjMrDqezs3
            3n1Lj4XIubl4WnAXqttQ4+PIpRTeGFJ5aA5JvyVNXE9nS2UmKwS8dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1LzNPYkh5Q01Da1RuYzE1
            Z3RybVpJMFBicVBaQmxlMGpDcTM5SU0rNGlNCk9LdWpWTUVKTlBudU5WRDY4VXBQ
            SDh6NkFkSTROQkhCSk5EY0EyZjNNdkUKLS0tIHJsNkQzY0FlRTkwa3hxcTFlRUZH
            TzJpZWdSdWo2RkZWSmJRVUpDV3hlMHMKqDVAtfiqXF3wRyzHtRRg5WoubXhDMpwA
            1L13RwGYRSjCFG8PC1Of6d5/ev2y1dgNHsxEdFCHlaTLnY3rpEQ+1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:20:37Z"
    mac: ENC[AES256_GCM,data:Ysd0GqDAlEoML8E0ewqZilD5mdFfI1pPcQ/KpyNRiXU+jaybQrp5H6ncxZUV0QmaljrW9CGyFH4EOUWVfqVkx+N9gQkU3PSSsyAe02rtZSdwhEG/z0jBNNAoGHpbdkhRS/s98gRAtQ8Sms6ExBGv319X+lYmGKr/PWARnUJc8mk=,iv:ZCUbNXHK/Cu/a5Aoe0lZFcXkBTrKFb/gWv4aVMJWo2g=,tag:LHo/pLpGAW7HMzN6l5X1aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
