apiVersion: v1
kind: Secret
metadata:
    name: admin-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:OeJmXKEk++I8r1XY2GQ4mg6fWkh3vwbqACc2LFd89QbRthQek/RHg2vjJtgtUKQ+Y7Oxju1TNHKJvD1Xekhx0jc6x4Q4USUu1oxqtKxRpmxpx87TPvXVa8HSOmOiv2Eox24BGG/iRUKJpSNsNtgml+0C5/Besw==,iv:CUQ24iTWqlIXD3310jqRumBdtELBQvka+nbXU7GioKU=,tag:hrG3MfR8kTzqVDckfLVNRw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaVlsaGtTWDdpV2FVbUdk
            eExaRnI5U2JXcncvZ1RYVWZZTUdpcWliV1VFCmRQRmNwc09scnZMZXRWZWNVYkdu
            MmxpL3FRL2VyTmxqVzJ4amN3YlJVbXcKLS0tIGc4SlNGTzA3cy9qbnNzRkZuZ2JV
            M3kzSzNNSVZKWlltVlZKVkJCd25LYTgKutOEzyHKHKX0h0vU4J+guLDyLEbICMQc
            nZYVcsy/mfSQkbTxAWTW8tr9QEwM1Dcdrohuh7QAtBmI6hhuWSbtZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z0ZkeS82VlZWaFY3Z0lG
            M3daVHhLaXdkc1NpbFFuSU1TUkVvaHpSN3pFCnBRb1owbXFDQWRTd3BXenBDOFJN
            S2d4TWZJQVY4cENFTVhaWGF2MkFNNlEKLS0tIHB4a2hPYkpqZy9sdkZNYXQrNHBn
            TnpFZmZ5STlkR0F3RzBFeUFyWlV0R2cKVuTzFDSqRwkm0WsgumjmRX927z2eeL7n
            R8CDFqY9rUZJvxYgKK2zq5tsbJcUkCkLR48uOIbryf27GEav3+e6KA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RXdBbDdVaG10QXFjR0Vn
            ZDJ3Ky9WalFjdlVodk4rNlgydSszWDR4L1hFCkdVVUJvb1BsNVcvc3l3aGV1RkZa
            ZjNRQTlqK1VOb2lvMmxYeUcyeVQ3c0UKLS0tIFAxczNJZ05SVlczZElmUHcrcXdl
            VjB5TUo3UVdLWFpXWEtCSHNtelJCcnMKY09+Ev7Jg+peJ5yVGWjyzFo38RPSf14/
            iSDmQtdRkrhAOQM7BviBch4+YZ7zbkYOVZyIfZFp0EoNvtrLomnpoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZHgreGtrYkd4b1orVVox
            bWk5bDcxZ2V1Q3c2WWthTmxod20rUG9GZ1RVCnorMzVDL0dZRkp4a2pIWXZBV0Ez
            Szk5THRrVnZDazdnSURiN21yWFUwTWMKLS0tIGpJQzVodjlteDVDa293WGl3Y0h1
            eXZCenJ1WHNVMEJIcFFmcmVRNkl3VEUKCa5M6jh81G/l/CJ1uh8Yn9iDwsSFQgKe
            R0CHEdKINtynLerIK5ye25k3dBm4bFYXWRbwJgl3XcbVo6HYsL7d0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:21:26Z"
    mac: ENC[AES256_GCM,data:4iyz8Sv39zS6U0AeVB9VOX6qkC6ZRd3/fVoUaRlWXg+ttPTkgQ+K+JrHLJ8wDhCRTaPj2sQXJpy1uopNRS3Ci6aXkzR9P64rGVlhxxqTcMyfLXKX+h684dNRj/2BZcz7pFH3LiY4BPj7F5+X+s4ZXKuyMKkaO7E83upQoG5Spu4=,iv:plPNUcm9ZKpXXIQzASm4rGi7/w+SDQ1z8618VtF8+mI=,tag:D3Dufvkb6ynEK+V/iQgBSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
