apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:CAJCefBpD7d2ipId8Bkc0smLTtaLQRDI8UlxfUSaw3k1JB8bn1ZNSQPl4BKXSkKI9KiTy/FvGcrzjidMOsTyH6FvQzg0IQCogex9Rhw8MbWZs2gGTFqBupSX/QgrkDPWgzoWb/L1MuKG,iv:LdLikslfQ+o/3jqepVCUi5VuuC5dqjim8txpb7+KuZw=,tag:UfoB18Z+IqJ/3MXEadgPgQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRzVxeVk2bWMwZnRFMG9Y
            Zis1S3RPaWZJWVd1bWtCT0ozSHlROHVOaDBJClhLMzZmaGJlUXpuTXA1NnlXa2FE
            ZDJSR3Z6SkpMVWdoMjZjdjlqaXcwNm8KLS0tIFpKbzZUU3RWUzY1blVZbEdXYnJD
            MGh2OGJDNFpJblNYL2NweUhMeEh3MWMK8SjfXPKJ+yZl1RVC64jStmugH9REhwG1
            E2maXMeHgqCQ8YQnRQW2Kk0Dg1lc6EtIqgCJtgB3FI1TJJ/kjje4gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0Z6TUFGaHNSbHZJL2pP
            RFVsNUlPcWhuQVVORzdpS1lYdGNER2R2M3kwCjhBM3RweFNRMDdBWFNqYlJUQ0J4
            bnJoTjc3UEVXVit0UFJWRjg3cVRmSXcKLS0tIFM5SDVxOUNJZkJuWTAySzNyQ3RQ
            Q3JEUTNpUjd4VVdyTk1meHdEL0VoTkEKDVO/w5PIG2KGdRrihKPrSFbHbVVII48A
            N3zIsQLAo5tl7eVov/ApxlSSGqbkcYJ1EiMfQN+Eq6DuH90egYvE8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYURqLzhNQ0x1ZXhOamE5
            ZTZCNERlc05vOUNBSzdlSkZNS0JNKzBoeHljCjJPTWQvQkJyUFlETWdlbzV6U2Fz
            MWxYNzJYVGZueFVxWEx6Z3FIUUc1NEkKLS0tIE5HWEVsUlFGNjV2anBTWllkeDZy
            RmVhNFV2MXd3N0sydG9tS2sySyt6Y0UKkxy3fzbFFAc8f6qS/mWyyADaCceAk2BK
            +qrs8GXLP5pPclALqz6XlxeoicZXzLaEEwcPSD/8shOSp1YwNvwfFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SGxRbXI4ai9mLzdORDhE
            S1BxT0V0UDRyV1VzNUlxZmxlYkN2a2s2NVFJCjRuZExMUXBRaXphYWRQUjFlK0ly
            VmRUaVE3MU52QU8ySkNwL3p4NHU4cjAKLS0tIG5XbmdYTC9IZFpvVFM4YnBsbERi
            RXp5U3NSeVd0dXc0RnBVUGlvTjdPTWsKAuWMS/LyZDqtZEsPdfhEScPl+u+lYYLw
            rf4LAE/Bs0OZvsSTs+a9vxvCPpEgj+uAjh8ztH/hXzvsAWUai3yTYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:21:34Z"
    mac: ENC[AES256_GCM,data:o8/8mYIrBzliAXAvbIXZhTKR17SbPqqjntIitHPnbuILJmCgalkmiqTowsRYrsbJy4XgipA4z2c+SPTDY/8Mus70PlSQu1wwU7SqUGuvNseHK7foBa7u8pKoSwMOWJ6minkna4HjaEVNsrKvVS14Iu+LakSCWZtWT7NA9u+lmrI=,iv:xI400Vs3wv4H+6itWvxDtapKZXUvy3LfCl2l7LG7eds=,tag:TVZZO15ynNB5RvLBa7nCxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
