apiVersion: v1
kind: Secret
metadata:
    name: smtp-secret
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:n7Z5Y+4ZHikWv/9i3KyZav8ofw==,iv:CYH4Cri29AwLsc9JmgkfanTrgekJy45ZkD2UT/jcn3E=,tag:9L2hBGRn2egaKfUVJOD3hg==,type:str]
    port: ENC[AES256_GCM,data:Lw+0,iv:4GKjVGQf9GNdNDNTgBtHGHFiQedjctuu4EbtypswCMU=,tag:qraTfWbIMO+lwPnso1QFyg==,type:str]
    security: ENC[AES256_GCM,data:ut1JBLRKqYBJ,iv:nKsM0rcDKYLBu4G5vq+HlMeJyJFLCee/Tey9Wr2B1qQ=,tag:ZfI2c4WrI0njPebSC4D0tA==,type:str]
    username: ENC[AES256_GCM,data:FXFZiHqwarqQDRzH+gXk5gS6TmAR,iv:Jg8lQk9nLO63H3MLxdkj7ZObO2tt2CaPmsmoyjoZBuY=,tag:AiwkxTnCG2c3FlyPL9cgGQ==,type:str]
    password: ENC[AES256_GCM,data:q5xivSoklSrxpxev9l+aRbA=,iv:C56vMJXLUQJet5g1iTD/TXpkQCwo+SMg1MrOiTVLtdE=,tag:eI499mguEzrQoSIu/0uNAg==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTkxNMjlWQjdwMDJyZUN0
            SkgxdWJSWHplT1NyUWdXdmppa3dmTlU3TkcwCkt0Yzl5SWRMUmlSOURScWdhWVVP
            dUFHeGUxcGFkRkJKSGVtUjc0ek9mSEEKLS0tIFNYc0pSSjR5QlZnUys2SlBQMDho
            Ujc2c3ltb2FoWU12U25NTjk2YXRVcjQK6xaDLBV6Ii6gupGpprQsNDXF/9gNU8fk
            H0Yiuidtke1Xwj7g9irJFn7hnr2WtwtWHkoAXEtj3ZkNrqWItK9LYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUkd1OHdXRm1NMGdxNTNB
            SUNhcXZLYkRwN3AyZXlWWnFpNlpwUVZvQWlzCkpmWjVBSFA2TWZmMkVvQnpTTiti
            NS9BMkVjcGdlZDBnVnhMREN3SDg3MjgKLS0tIFVCRmZYZmR5YUZLT1c3TE93K1lJ
            YXJzSk5iaTZ0dXRPZ2Z2dG93aU9QZ28KF/zuuJOIAzqlY0asZwdtGOeWr1TxfWJf
            Z0iZ0m56itL7DaDMeWxqH3DKx8DXUGUduRu6sIOGMciKSLNC9g/zXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c0ZHL3RkcFBVRHpmallv
            bi9QcUhWTjQrNmJRdUxiaGNmOGlWaGVpbUdJCnAvYzJteHorMG5BUHg4aUk3eTRl
            aXhBWXd0czZBOW5oQ0c1S1k0OFpwb0EKLS0tIDBHa2FISE5UdTBJU2VHUVZDZWJK
            S2tsWWQ3V0w2b0lkUWlYMkJrekVSRFUKxrHOYFqwR0UCj8rt46RQTk8z+N2WIQzj
            6XNI7CYNgVCYtXWGmigodKQC6bAHUY1XaAyq+AQAhsj33VadCyYYRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bGpCZmQ5eUlTTXNrYytS
            NGMwZUtuZzN4MnljRjJ0VHd1clJEUGFPalVJCmQrM0tQVG9HTDBXK3o4Y2c3QnYx
            MVUrMVA4ck5LWXIzWUhvY001MlYzZzQKLS0tIHdVL1NBVmx6aUxaN0pSWlBzazJF
            NksrbzRndUI4RlNYaDJsNFJ1VCtIRncKcRrlp5cfo2qrrlAMO4/Lcvz9kVt6cQ3r
            Wp2H+BiqvbMeAXBujWNSES72BsslHLA/MO5v/Pushz83TBMZDV0lsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:21:40Z"
    mac: ENC[AES256_GCM,data:wo5diIUnoQzYuAf+TQf43Xhl1qjDvKAnqr+FLDtRpYsZKQtStUetdNqfJMFVQ2OhdJVW2gLABThdoAMKa61bjGv6HI8lHLKT32R5m8UDeHq524DQUSgnwKuqA3uwYh7CtzyT1dZ6gEB4G1SxPl+MlUU4jFO6QOf7MfUyp7sBddM=,iv:bS+LJgKltIEq7uFGc0GR7/6IhtZKmcBkRpczOrk4F/g=,tag:02r0i4wcCEV5mIdwzoBbrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
