apiVersion: v1
kind: Secret
metadata:
    name: yubico-secret
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:eAwXb4pN,iv:kL8DOOrgNy0pX2MJWoP3RN9jbOxx85yuozVR4jBTumc=,tag:S9eEFJ6XKBX6HiR0bb5jpg==,type:str]
    secret_key: ENC[AES256_GCM,data:3fyij/aTyG5pn1LOEa+QgEJio7HaBq/12jWxjQ==,iv:Q9DCAkI0ZCuKFqQUdCQBfOwesZ+eWr5xLWI16qfxsdU=,tag:E3AbgD5X1k+BNW5y2JH/Tg==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc2VUNHZHdElsdHRTTUtH
            NDFvSTlwTmtiOENBaFlMb1VyL2JnMTk5OUZ3CmhNTTUyUEhleDhNbEFiNWFldUhQ
            VGlwRm1tWlMyY1NKZmJOTW1VdlRlem8KLS0tIGZxdzBvRWVHd2M4RTl3cHJMVFZi
            aDNTdUUwdmhsMldqa3VNTXJEZEFhMFkKgN5CnzygwoE+1ZgPTqy0kCHpAHYMW2ON
            4V8nrmKJJM9UkNZNDo+TsA33/wHxcA1Bwm9gTfmxHfI5GMC+SepvgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMlBjMjh2dHA3RENPWHZE
            K05uaU83dlZidDM2ZytIZU5tTFhOcDBVdmw0CnhLSzZXUFRZdEFLWGxmSGtlaFZS
            Ui92dG9UQ2daVHR4TVRrRU5Ca1JiVjAKLS0tIDVSLzNYRE5MZ256Y3RyRUlkOER6
            VzB0YWVLUnZ3M1VHNTRyNXBPcTY5K2MKMQu7q7qJitSa7ugArkZaFLQuFcVxj9xL
            F6vptUMDqGVmSl5+GmeYh2RuY63HiefDGLEfAwyce79E3cc3k+MZIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYWd1cjhuWUQrMkFvZVg1
            T0lseWY1R0FpSVg2aGNTUmM4cUpadFRVZUJzClNSRUJXRHZiWElHZk5pMGY5SE02
            eERScmpuZ3VpOGhNWkVCRDVxT2xFMVUKLS0tIFFmTFhHbEh1QWpXN2MwUGY0bmRl
            NlVFbXBSNiszdDZ5NlNSNGxoQ1BZcWcKqeJr0Dg+UpT5XvUE5G8iWdEH47vUi+To
            JIBPIYnIm+I2+mQXG3swahxlKPmkB3hf1hr0J0b/roYOCvn9hkWfmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNG9WNjJBcDZ5V1JPOCt6
            NkxscEUxMlRnM3YvbkI0aHZ0d1psWU9vR1ZNCjVJUVpWRWp0S0dMQmdlNmllb1ZL
            MmtqdmprTjgzblF5WStlWGpKQmlrSkUKLS0tIEt3R0s1bE1yT1h5L3JkcUsrQUxR
            MjYvSWJrdmRFQXd2WEcvcGxybVkrUjgKGp9kveT71OBoa/Yr2XXuM0rHATo9y0cB
            zEXwaoYtM8RNXBqjtbKOEEeyuPKHhaOLzraZjTomSm2SesuLE18dzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:21:44Z"
    mac: ENC[AES256_GCM,data:vU5OzLw1z4WGcBfAdAwatAgBW3Stgd3OzquQHD9P2oLv2707hF1cDgasjI4cv4wIetHdGJ6JYoPwjCDuXloU0tdhBAljvyl3kWjGFZeb0aLgJBQ5L+L6Uw6OCEQIwH/krKQ4jpIajdMcO8eB8CeNRX09OaoRPRh4BmmnYg2W8JE=,iv:0vukgQ8sfsM4l0t7HeINaUXY7xukA42/0ygfuruyr/Y=,tag:jqySyrMjSK6iInAHctFspA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
