apiVersion: v1
kind: Service
metadata:
  name: dozzle-service
  labels:
    app.kubernetes.io/name: dozzle
    app.kubernetes.io/part-of: dozzle
spec:
  type: ClusterIP
  selector:
    app: dozzle
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
