apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: niles

bases:
  - ../../../../../apps/niles

resources:
  - namespace.yaml
  - secrets/calendar-secret.yaml
  - secrets/cs-config-secret.yaml
  - secrets/lol-config-secret.yaml
  - secrets/rl-config-secret.yaml
  - secrets/smash-config-secret.yaml
