apiVersion: v2
name: vikunja
description: Helm chart to install vikunja

type: application
version: 0.1.0 #Should be incremented
appVersion: 0.24.6

dependencies:
  - name: vikunja
    version: 1.0.0
    repository: https://schmitzis.github.io/helm-charts/
