apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: dozzle
  app.kubernetes.io/part-of: dozzle

resources:
  - deployments/dozzle.yaml
  - ingresses/dozzle-ingress.yaml
  - rbac/cluster-role.yaml
  - rbac/cluster-role-binding.yaml
  - rbac/service-account.yaml
  - services/dozzle.yaml
