apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
  replicas: 1
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: ghcr.io/dani-garcia/vaultwarden:1.35.2
          resources:
            limits:
              memory: "256M"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: vaultwarden-config
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-config
                  key: DOMAIN
            - name: SMTP_FROM
              valueFrom:
                configMapKeyRef:
                  name: vaultwarden-config
                  key: SMTP_FROM
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-db
                  key: database-url
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: password
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: port
            - name: SMTP_SECURITY
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: security
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: password
            - name: YUBICO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: yubico-secret
                  key: client_id
            - name: YUBICO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: yubico-secret
                  key: secret_key
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 3
