apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supersync

bases:
  - ../../../../../apps/supersync/

resources:
  - namespace.yaml
  - secrets/db-secret.yaml
  - secrets/app-secret.yaml
  - secrets/backup-secret.yaml
  - backup-configmap.yaml
  - backup-cronjob.yaml

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: supersync
    patch: |-
      - op: replace
        path: /spec/values/ingress/enabled
        value: true
      - op: add
        path: /spec/values/ingress/hosts
        value:
          - host: supersync.yohanzbinden.ch
            paths:
              - path: /
                pathType: Prefix
      - op: add
        path: /spec/values/supersync/publicUrl
        value: https://supersync.yohanzbinden.ch
      - op: add
        path: /spec/values/supersync/cors
        value:
          origins: https://supersync.yohanzbinden.ch
      - op: add
        path: /spec/values/supersync/webauthn
        value:
          rpId: supersync.yohanzbinden.ch
          rpName: Supersync
          origin: https://supersync.yohanzbinden.ch

commonLabels:
  app.kubernetes.io/name: supersync
  app.kubernetes.io/part-of: supersync
