apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:jKkb5Q85k1AeUL+T/5LvkaZIcC4=,iv:FJqOmw2VIWfG5YFbOJlcG89MxMCafCsgYXtAbdaiPaU=,tag:Kubgpxw5EhxM6mKIcwrAHQ==,type:str]
    typesense-key: ENC[AES256_GCM,data:aeBWZ9qV9JFIE8oFQyNus4rRCpA4PXVhjmdURXQrdNE=,iv:rzgxkYvMyHOQ7OKKiaXLtXOKFOZLPXoQrNNXrGdZGWY=,tag:M/kOLVvawhTtE6DAKnIZnQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVzBYdngxYmpINDVtckFz
            MVd6NW8yS2dWdFoxT3EyZGNRenVUazNNVkM4CjFuTEdTVXBzTVJSOHNqa25ybUdJ
            Z1RqSlFxZytDQWNqdVFzOW9tbTZEbTAKLS0tIEZzRjFCNDIweko1WEVncWsveVA4
            RkhBdzVDUi9DckZXZzRJQzZzRTJORUEKDFWHxyPeNenjtqoEk45NBsBRaaxppbjd
            Cb6VtQLk6XJzJhsWmBPX+KMXo9Ny6HvJi8OkZD+YBa4To6k9igvihw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ2pDeUxWdTlRbzJlN0Z6
            WTh6OURYREZzZm1abFBNV0h1NU1UTDlocUFVCjJlbHZBS2MySnpCS2p5RHVTMXBW
            WmlKRUhqUThDTUdXMWl5Vi80NG9ZYjAKLS0tIEZ2TDNaRzY0MHJ2cTFQYk1mT3NC
            TVBscm1NcXNYNkNiaS9WZGJLWm9xWEEKYV6hrarUpf9NVfhb6oXzbWozcgDMXX4/
            LkwUOkWVhE9mnagklqeKiUShlx8h/za0ybie4rD22oZKUP53awKVHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbVcrTWdmRUhCb2dBZGsz
            dnpseXhuMDdLUHVnTWNLNzdqNTUzbExiVlhnCkNqUVgvd1Jvcy90eDJya3p4OWRW
            ZWdWQ0U3ZGtENlZYcTUyUzhLRTdRYUUKLS0tIEJzNm9PWEJxMS83RnhmcGNrWXpu
            Wi9ubUs2NTJuMmlzUENlUTcxUmE5L28KF5Qv5UxIE3FcOYa1pPraI2NYoVx3jvGR
            rkAfQnI3twijPBzGtM2SJV41Go5TiVp1RZfqdBxVF3O8KCihGuIuMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITnRCUHFuWjVCQTV2eE94
            dnduZWd1UDJUeW1RZUs5ak1kUWVPd0FYUkhBCjJ4bmZBMS81SE81U1JONmJjZENu
            cjdORlpNbTc5RllVZFpNY3NCYnlWK1kKLS0tIHNhQ1VDQjFzSzludWROaVgrOWxC
            SWc5a0xEUHloQ1RnSjVlVjN5cDhFTDAKB74IkIaaAZbw4Mlc1X3+x2/6U9Lv+I/H
            WvISZptiXbTjfRGSXdooiMxOlVBf8vZkeUO1iVJpmVvmNPpBIPzJQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T16:06:39Z"
    mac: ENC[AES256_GCM,data:btaiBvjZzDax56tw6Eej87haWU0Bqay9rbAefQM47vPh4C8ZyHTpFikq17Y4F176gQVFxPgHuZ3nd0fbyM/PijCQI4nUI3IAyMqNude0QkLDcJMLYWnhHfwmG2ROOAqoiX6jJwIIbDnByJOYKm7LhXDW7QATLvs6uEuRPB8VEZo=,iv:VhPRBl+GaMnIeQGJeVPN0e8NzOl26jKWk3o+QJoiUaM=,tag:Xl4rT/XOt/U9E7bKsD0aFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
