apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-config
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3xghcOvVGXmgVEgFAak0kmpeS9Yt8A37KRZJMQR9GqUS1Yg=,iv:ekZL0xyw/l8GRYfm3MuO/sFyxC3LzDwgvpyStlpz2YE=,tag:2gsTuuzNuQ62X5iEN7syHw==,type:comment]
    webdav-url: ENC[AES256_GCM,data:1k8IvDQEBpExJHw98uJkllHzXXxcKS/QovBZmbSgGFsSPn5RUGC/DaKBwpHRtP9j6YLaP5CSmAa2U5rS,iv:WMFrNbR7NGd1xpk1gfce3ZbG6g7zEemBRkyZuUu4u2U=,tag:w/ETIMfAms+fh6iEl6rCQw==,type:str]
    webdav-username: ENC[AES256_GCM,data:C02k0s3hDdglR5nVxpyZiKyUwEkLOtM=,iv:AvnsNtTOaJLHuUvCKbzGPWuJooKyvfQNx/1GprsMX+I=,tag:1boIk3BU4EMA+3udOs59Ag==,type:str]
    webdav-password: ENC[AES256_GCM,data:Ow32amHQlfo1NZPfSKqeMg==,iv:mEwtpfusrlkOnYZTBwqFmGqwkLShjka9ecYXbAi6sTk=,tag:f1in+0VhT7MUfy+QL8x+6g==,type:str]
    #ENC[AES256_GCM,data:3zgPBbhpjKVcT6MaCzeFu4fNOEpAdfNh8/owDT7JjodwxdOgOlpSneC1mRQ7R7xguaemwyoom4s2z14=,iv:47/LFgVsDPCOjqb3ykPrO3gMEOZcaO3y7MlycKyxyZQ=,tag:wqpY/41NFN/XF8FArcs9Jw==,type:comment]
    ntfy-topic: ENC[AES256_GCM,data:MRALNARP5+/90xi6p8PJSUBcyDD33GHPM3g+hCK5Xu0=,iv:w59doWNKwXqgD5mEt2LAheaqzVk57SvZysI3AVzvCJo=,tag:iMLm9eEVqkela5UbjBJOKg==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFalVZVE1BSWlYNlRPRlk5
            bk1tWFJGV3pNZ2h4NlRyVzltak9aY3M3L3hBCkkxcTkrV3B1R3Z5NU1IYm83TGVm
            K3dQUEIzYW1sdk1jd3FTbXEzUVprYVUKLS0tIDRKQXU0eGJCYmxLQXIyY0xHdkdG
            TGxpWi81b0xMUFhLVmNGQjZ5MzF2RG8KnU6EuWoEqIGIIwawGbTC9R4HxKGpLm3/
            R2DCpXHWN1UgPK2qlw5HcoHeARyAsvbsBEob5Wwfe7wMO4wZKkO/hQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MFh1SXErZ1R6TDFkR0lx
            MWI4emxiVXRhUTRNZWdYK2lDZHZJZVBMRENzCjVKZmdRWURBMHJKYjdnWDdCNzNv
            cmszMEExZ1JTRlV3WGMxd3JVZTZlQmMKLS0tIFF5dkxJaS9peTBRalJ0Qy9XQVN6
            cFJ4dG1tTnZtdVJ5dzUwanZ2c2tVc1EKrOlyGRidKYiIzdurysdW6YjNH49V2s3h
            aF/IrxJGbaLerDNmaVa89mSJnaTsXMw2i71Laa/MJrZtUKjwoAkt5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSUVQZlNDL3dTUnNZV0VW
            a1cyZm1lcnFhQWt2TUNnWXphYnRPZlRXSGtnCkF6M0kxRkdzMmRiNG1Uc0NZWHli
            bFNMT2NjZjZXYjZNMGQ0Rkk3aFBpeWcKLS0tIEFOOVBxVGVTYnI5VGNZZjh5Z01G
            NmVoRDJ6OE9vZys0YzFFZzUzWHk2RDQK7eF7nMALaQHJJQJdcJrOhp/HBMtEYX4L
            gJFc4wc5JRptYasbKnguIjDEqTb+wu41RBZBJRDSO00+fMwAUaP6hQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibWtPZ1UvVm5melNaOTh2
            TVNuQUQvaXdOWUQ5SUpBcy8zOXRSNGlYalhvCmRYUmZuaGJiMEFxTVBCeGgyZXdR
            bVlSTm1UQVpSQUd4cFZSNVlUbGljRTgKLS0tIHdYQUV6VDQxUEFLNlBpMCtEcjFv
            VzMzZGtVb3VFOVJLRExadlVFVFN1NzAKW+110hDu/qDTeKxgxE/0FmHRG4qE7pUQ
            TvWtopop3U7pLNWnQGT2fIso0tvogbo7G4B70XjMU0fQoJ3aL7WS9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T14:55:37Z"
    mac: ENC[AES256_GCM,data:Os4b0izCndQS9j6HtyLFDZR7mRCj6T5vx9zHK4vDG3RZBTDHfFM//JfUq68LGupxVKeBSKIltcWtjThS7vKp1eNP404NJAeCmMOjM5Sm3PyDU3j2d3FsiITOME+W+KGiqO+R8HQIOrr5372vCjPWz7cE+JqpAQBdz2F1dmN1wqc=,iv:HBwjjYKGYRhl1mOpdj+syG+qdWI8jhnuRNRHRD+yCMQ=,tag:K7npFc35fwivBOHMefhOjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
