apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-cluster
spec:
  instances: 1
  storage:
    size: 5Gi
  managed:
    roles:
    - name: vaultwarden
      ensure: present
      connectionLimit: -1
      inherit: true
      comment: Vaultwarden role
      login: true
      superuser: false
      passwordSecret:
        name: main-cluster-vaultwarden-secret
    - name: vikunja
      ensure: present
      connectionLimit: -1
      inherit: true
      comment: Vikunja role
      login: true
      superuser: false
      passwordSecret:
        name: main-cluster-vikunja-secret
    - name: jellyseerr
      ensure: present
      connectionLimit: -1
      inherit: true
      comment: jellyseerr role
      login: true
      superuser: false
      passwordSecret:
        name: main-cluster-jellyseerr-secret
    - name: supersync
      ensure: present
      connectionLimit: -1
      inherit: true
      comment: Supersync role
      login: true
      superuser: false
      passwordSecret:
        name: main-cluster-supersync-secret
    - name: backup_user
      ensure: present
      connectionLimit: 5
      inherit: true
      comment: Read-only backup user
      login: true
      superuser: false
      inRoles:
        - pg_read_all_data
      passwordSecret:
        name: main-cluster-backup-user-secret
