apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

bases:
  - ../../../../../apps/cloudnative-postgres/

resources:
  - namespace.yaml
  - cluster.yaml

  - vaultwarden.yaml
  - secrets/vaultwarden-secret.yaml

  - vikunja.yaml
  - secrets/vikunja-secret.yaml

  - jellyseerr.yaml
  - secrets/jellyseerr-secret.yaml

  - supersync.yaml
  - secrets/supersync-secret.yaml

  - pollenzo.yaml
  - secrets/pollenzo-secret.yaml

  - secrets/backup-user-secret.yaml
  - backup-secret.yaml
  - backup-configmap.yaml
  - backup-cronjob.yaml
