# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lol-deployment
  labels:
    app: lol-deployment
spec:
  selector:
    matchLabels:
      app: lol-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: lol-deployment
      labels:
        app: lol-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: ocr1 # Since it uses hostPath

      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: lol-deployment
          image: ghcr.io/yoyozbi/niles:v2.2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 150Mi
            limits:
              cpu: 200m
              memory: 150Mi
          volumeMounts:
            - name: config-lol
              mountPath: /usr/src/niles/config
            - name: stores-lol
              mountPath: /usr/src/niles/stores
            - name: svc
              mountPath: /svc
      volumes:
        - name: stores-lol
          hostPath:
            path: /data/niles/lol
        - name: config-lol
          secret:
            secretName: config-lol
        - name: svc
          secret:
            secretName: svc
      restartPolicy: Always
