apiVersion: v1
kind: Secret
metadata:
    name: bookmark-secrets
type: Opaque
stringData:
    passwords.txt: ENC[AES256_GCM,data:vsFQXyosLk9dgqj0mgYUGOQAANwV+NxEgh80FL2/cNtlaF2mtxiysPLYs70txFB9MEQQySd6IY72AJy07cutfxbAjggnDkmw1tHAdYWHAUOydC0qTjd3t7fqQ6fPwfyIldsFROQ+XQLpdsBVZMe/nhb1GTKnSbPTYarrXscTL+IHlViBbH9kGbwLm4XHD1gq8ZcPKFp/D7U6N6sp3eR04eUOQtesIgewKOHxTRtPux8Z1RwJ7NdNYX46DE9T1CVzX2DLFTFGnVy+BvSXPstIfB/zIW5NzmvZ+v30BgeOzfMaWwFcErzOw1a/yfdPuU49ppfxe4aLlFG1DYeYCm2gxTdT+y2GflhK+Y3+2nagtKjCgUDg6BJRnoAzF2UV6UU6KyFvjVnbYtwBPNgayuNKeH6BCfkNn8Tiwdr0LqVjysq6kHvkGO7qt/nP8wg/63nfWg==,iv:Z9ZFGLA1RbW/ep/CUNSQ22lniO4wuxA9unfQldq68Jk=,tag:HJ1wzzKSo0SHiV9iWrYWmg==,type:str]
    secretKey.txt: ENC[AES256_GCM,data:vqF0H4VBpRetoH1seWCsChFxOH8=,iv:lXFiIAT9uPSav9Rv2pT9YPrDOu6pavJkep0qrG6buXk=,tag:KBh1AFRpgdV/y04EQ4qjyw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdWVKdVRPZFZxSk91SWxD
            VzRTay9RYzA4QjN2eE1HNzV4ZTJWWTV0QTBvCktTdXdKa3FteG4zUEorS1dSdkI0
            SXBlZ3gxTGloN213M1BZbTROd2U1aG8KLS0tIHZIcWF4Ykl0RHBjUisyOWx4NzBa
            dytLODZvWHJqTUVkWUt4MXZyTDVJUHcKL54nlWtYTxhiU/HfUmZmR74aui7ftJny
            h1fRI51eBViyCVI5Rh5CcW8Xi8bkseMY6ELJePCURK4LOSpBWT4NZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ0JsSlZjOFBHb281REJN
            UkpDamtQMzJyblBFQXVhU3VDY2tWOUNjTXg0CnZlNWMxbWlFclBLcGk0OUVuc3pp
            Q0o3UGt3eUhIRHJ3Rk5oNXNvUW5qSjAKLS0tIGRjcTFFSjJFa1AxQWZFUGI4dUl1
            bG93Y1Faa3BMTkFaTEhiaTBJYTNIQmcK6AbhqoJ5KiKsHrHPR4lzFm+9Yce00NL2
            mKDtEP/LGTAMOzThmTFo4++MnTWJReaTI4kIdi2+69yOffnIZXVhFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQjBqemU1cnRackxTamNF
            L29yQjN1TXlBSG5BVUp5Rzd3Ly9ySEYyV2x3CjVWQ1puTDNjZUVWcGpuazh0Rk5i
            TkNMQ2N4bUZubWc0bHd4M3FvSmVyR0EKLS0tIGtYTHg0UWV0OG9WN1kyc1RjS3oy
            bVNEeXM2bE80WUFzbGgrcFdGS0cxOW8KwtXjmY4o5RmVt6gSGW4J+GpsJf6HjbzR
            zAQgfksULaXYmPbBf1jEfp5vUG3W8pcL96GyA5QP8kU+zRp3HC9/ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbC9UcWUxZHRLMlBWOTli
            eC9nQXhNcHhOdWZ6ZmE3UkFZelI2cUZxVFRZClg4Q3FuUmIwVFl6c0ZKSG9DUU4x
            VFViTlNkVFREMkRhM3Z2WjJSbUFLWnMKLS0tIFZSbmdhNVduZHZLbWEzS2cvSW1G
            VnNWSWRLVTdFUkI3YkVVZnlFd21HM2sKRsRhYbFXvsiWnz98N7lj0Ys/QXxew+yR
            Cg+XnH7SBqFsK68C+54wwM/mpL98g/i92u7Fi5R7fsPeGMjLbh3slQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:44:12Z"
    mac: ENC[AES256_GCM,data:7T3IRgxRyeBKigILcGKOq7W20hJxS4LwfBopREpS1//WmM7FNrnpoPNddHNtZp1ifsyHFWHy+Bf1Lr4eL9V/pTN4Cbxng0Ake5mJTH2SmK8BspfbidAG/DUGk/Aj84qwUksPEIDOOi85uU/OFsgr3KGbqK/VqJFAuga0abJ4988=,iv:RydWac9tmYDbqlCWBjplexY10ngS+dASwsS4lhB8fr4=,tag:/FTUAbJiCTzMG7X7fou5kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
