apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: super-productivity
spec:
  interval: 1h
  url: https://github.com/super-productivity/super-productivity
  ref:
    tag: v18.2.8
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supersync
spec:
  interval: 5m
  chart:
    spec:
      chart: packages/super-sync-server/helm/supersync
      sourceRef:
        kind: GitRepository
        name: super-productivity
  valuesFrom:
    - kind: Secret
      name: supersync-db-secret
      valuesKey: database-url
      targetPath: externalDatabase.url
    - kind: Secret
      name: supersync-app-secret
      valuesKey: jwt-secret
      targetPath: supersync.secret.jwtSecret
    - kind: Secret
      name: supersync-app-secret
      valuesKey: smtp-host
      targetPath: supersync.smtp.host
    - kind: Secret
      name: supersync-app-secret
      valuesKey: smtp-port
      targetPath: supersync.smtp.port
    - kind: Secret
      name: supersync-app-secret
      valuesKey: smtp-secure
      targetPath: supersync.smtp.secure
    - kind: Secret
      name: supersync-app-secret
      valuesKey: smtp-from
      targetPath: supersync.smtp.from
    - kind: Secret
      name: supersync-app-secret
      valuesKey: smtp-user
      targetPath: supersync.smtp.user
    - kind: Secret
      name: supersync-app-secret
      valuesKey: smtp-pass
      targetPath: supersync.smtp.password
  values:
    image:
      repository: ghcr.io/yoyozbi/images/super-sync
      tag: v18.2.8
    postgresql:
      enabled: false
    supersync:
      smtp:
        enabled: true
      persistence:
        enabled: true
        storageClass: longhorn
        size: 5Gi
    ingress:
      enabled: false
      className: traefik
