apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: activemq
  app.kubernetes.io/part-of: activemq

resources:
  - deployments/activemq.yaml
  - services/activemq.yaml
