# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarks
  labels:
    app: bookmarks
spec:
  selector:
    matchLabels:
      app: bookmarks
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: bookmarks
      labels:
        app: bookmarks
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: bookmarks
          image: ghcr.io/yoyozbi/auto-bookmarks@v0.2.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: SECRET_KEY_FILE
              value: "/etc/secret-volume/secretKey.txt"
            - name: PWD_FILE
              value: "/etc/secret-volume/passwords.txt"
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: bookmarks-config
                  key: ALLOWED_HOSTS
          ports:
            - containerPort: 8080
              name: bookmarks
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
      restartPolicy: Always
      volumes:
        - name: secret-volume
          secret:
            secretName: bookmark-secrets
