apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 5m0s
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cloudnative-pg 
spec:
  interval: 5m0s
  chart: cloudnative-pg
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: cloudnative-pg
  version: '0.27.0'
  valuesFiles:
    - values.yaml
