apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - repository.yaml
  - release.yaml

commonLabels:
  app.kubernetes.io/name: cloudnative-postgres
  app.kubernetes.io/part-of: cloudnative-postgres
