apiVersion: v1
kind: Secret
metadata:
    name: config-cs
type: Opaque
stringData:
    secrets.json: ENC[AES256_GCM,data:Y7D2l/IYEQ1M/pOTQZNt1G1OOzDUkWlfaIRKNV6ZH9TpoXvn9jadVUsh8m+KbC/KrbzbaB0Q7rDqlRy0CzCtWe63/9roQUl/ZaWos5Yomwz7b/9yHmHfP9wRMk/nJvIW2c1ouSPBNWsXVO58cku69Bxv+jDP2FUgCjFu37/3LrH+rmM90rcNThrtG0qkX81sHhXBB+FD1s6I6lKic0gmnlK/DB7F03tL0S2Gps3ejWDEC5qQavCGgFIRZkLryCYBVEbyjKvIb05ZCI378nSwzMf5uYrzOh9mDCk7h9rwUXFjvrRzw4cS2XJVq9iFhQWFM9AZm/wzPJg=,iv:KnctcYd+ekzbyN0tHUvP/FWE6fNtyWbaoHKybOFSAGo=,tag:dzc8lDxIcMfGA/dYTh0shw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b1VsOTVWOGd5QmhBcFAy
            UjQ5SkhrSm9HaDNZeVNuRWJuRUdCalR4SHlZCkxVM0lHaXNzN2N2VWF0MEZoQmF4
            S0VYeXRNanN0dkpqK0lkZm5jR0R3UUkKLS0tIHpyNTMyTzRpQmNTU29tRDdJYlB0
            MG1QbFlIUlA5S3hncFBLelNtZlU1eHcKOT3FcMxKridzFi8dJDV1kh9d9F3kQcDD
            DUSkCLGhU0H8ulmiXy+6rR3W0WVAKSuKgnh6EnhCFb4logQXkIbtgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR1hQbmpXNktVOTJOSFhX
            T1htODNrMUVzSmlaUXdTcTcyTnQycWdzR3ljClUweG5udktWYXdzc2d4Q0ZYSHFV
            R1NFZTNFaHh5OUdHSjdKRmEvWTBxZE0KLS0tIFAycVg2MmhnbnJpRTBGelRDdnhN
            aWdaUFlwNUt4cHQ0dmU4T2h0MDhrSWcKROHRGjyT7IFlltk7GphSW+p6ternlvU4
            Ib5e5+lA5IH8Ri/YpKsjcsHuvKO50mtx3XFHNNDj78NA6aqPNNkUWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUXYwbWxoUFMrTTVCZkFQ
            bWRwQzNLRmhqZ1YrSVJkV1RpK0kxTGQzZmhNCmpjN0VmRmdXV3Y4TjRGc3llVnlG
            blVTcEtZSG9oZW8vQ0dQcFQrbTg2TWcKLS0tIHM1L3pzY3ZCdVlCbWJraHFOaDV4
            TllDUFNoeDJMWk9KdzNDSEpWL0lmTDQKISfN56d+Wf/o9ycFL1wOU+ZCJgiAFh0Q
            6rVdKTCTZx6244qbuBe04zlr9wwWEpxkOeoYY87bpJjT1K51MNCHLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZGpRR0M2MUIrNCs0NWE3
            U1NiRzNsczVSUjUrYm1nWlhuaERTVkt6clh3Cm9GdXZKK25HNHVJMzZ1eHFBNGhp
            d215ZmlUYnRCWFVPcFl2bzNVRi9hVmsKLS0tIFFvRmtXMGdRU3FEbWkzbWorU005
            clROck44SWJ1V3FJU1RwVGZWanN1UkkKAxYm4yeZjyMqtZPJGEfcRfld+Ej7VM0M
            L56NCan9J5m7JI8ZXlYYZPWsa6Ax3ta6qd3e3h4S7IqmSCgahtup1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:34:39Z"
    mac: ENC[AES256_GCM,data:AQxd0GfUqkrlj2hyeZqIfBHh5GDeuXVePFdShXkKa6/ddrTZhFrN0s050k0BPHtA2t6xhLOP5klvafAWOwOQaAcli3TVfP01bbdQLluB+9x+9ZzVhTazBJd8iO84lTFaUidDo1E+lH41DwtAFswXi5FRRH0Xsfo2YXO7245yvnI=,iv:fITjZz3Z0vYvnpMTZvewvJ1OlRLV5L3GKLN8JV3slQM=,tag:VsqO8brYhhfcEWSM8yZ1Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
