apiVersion: v1
kind: Secret
metadata:
    name: config-lol
type: Opaque
stringData:
    secrets.json: ENC[AES256_GCM,data:V02q85NYeTyCEmgxC+jzX2JSOghGi9TjdaogZoQik75CBChb1i7jhIK6txN7yqZBpb4P/Gr2GzyF8/j9C7Ds3lQCuCymdN/N1iFWjLw/gsSE0Xy+tOdslGqnK39ACmj5TIUzISbrPhsHTT42Ecd1mbi4MN68HXNGGjsR/FuSWaRnRvluxe/HAd8RgRfIBWIIs0R2HEru/XlKcDEPSYPfzP+pTpiJPJxhcq0o2PR5BDxtmlJBT2WNfzug+fP5YbMELZRH6Vp6WXoncL401ybF96nUcj0NWtG3EPdtfRFpv25ZA+GUkjYvm2Mp1fnAwGLLyx8OTvsm6No=,iv:doA0jQ4jkZj4VCpp1xUeFrA/VZmygRpGwKPzlT0RlNA=,tag:frY6uidCoIq0AyKy+rzIaA==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Zmk5bWJEbE9HZjhWMURP
            VHQzdkozRDJtVi9hYjVmTjY3UjVpOG9qWnlFCm5zakZKZU81ZzdVSGUxb3dJR0tk
            QmJQaEhwaVhtQUp5N2VkZGRIU2RGTlUKLS0tIG1nRkF5WkxZcEJzNlQ1WXR0OVdR
            R1JsKzZ6VEFzYjdEaDVyRDlnSkRKSEkKs24+alpqvkdlvv7Uj4q5nd2J2y3ITBpJ
            FkuUXaj+EnbfuYgU7YSaHsHIzj6JMZpZ7KVBsSPPIHKAu3W2JZVg5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxV1JiazROTStqaU1jMGhm
            UEpzdTlrTlVzZTVFOXpKLzNDT1lSekU1TTJnCjlPWFhuWVd1amxzZmFPcVVYUkYy
            RlpSVUlMbFpwMmduaDU5ejk2YzZOYkkKLS0tIFg4ZkJHcTh5N0RLNlVRNlRUaURT
            L3B2WWVJYWx3RFJqYWJBRDZBaTNOd3MKWuR3XFtnbd3UvRYPo0pCkzbAO3HIbAcy
            3d8tyuZLfDloAp4jF2PI3U9Y8ulN3YPo0aliQ62RefjkspOZUSH1+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeTFlcHBBMUtsci81NGli
            TWhld1A1cjNtRVRYV0plTk9HYktMeTdwdWs4CkJiU1MwdjA4VE90VU8zZU1jN3Fm
            cmhFODlZWTcveE9UTmREdXErMkVFTU0KLS0tIFlmbXlZRmkzaXloS0c2Q2h5NXBp
            TFVnSGJVN3JDbzREcHd1aWJSWjVxN1kKxl5MqbecLCT80nsILDkjEHUlo+pH5VQC
            ZD0P/p6v3BsB0K5fm2r42scs1vGm0yyXxU/+aQ0hW5jG8N5RrxeXgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5V2ptQ0s5UkhSd3lRdWhN
            NStFZnFqaUFNcVQvU0dnbTdmNkl2aTF2c0RzCnp6RE05WWNYK0NDaDlvam9RRDJu
            TlNtQzhPdzJEdm5qdXpaYit0RDZjT1UKLS0tIERNamNZaFFWSDU5eWZEeFM2MUxN
            ZlhQblc4Uk93NW96TmtWMHpkR3lEencK5nItkVZV3r02X6Ap0JTmXhiuchcTSCEy
            0Xrc68IuONqoE0NaMRJT8Fb3NN8VRZkQvJ2F1mLcmKM4XLzPUGAmyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:34:45Z"
    mac: ENC[AES256_GCM,data:ve6rUDCxwzLk5c43h+81W3BjPmIrySkejkqgMmEbc8rqloLotXAmRvhiRDgY/C4QnHTq6hTLDU53sTVf0mJ/VSXVCM165fwtgJmFOBGwU+7tQDu/Ct9yzBccB47WQ+8sNG97y3bf9My+EJHimPoeIbsJQG6xqkJMdHU0HuAt9c8=,iv:vh9cDN9/YZbvDmCk4plbAKkZIi4ppOcLMD0Yv5+85zE=,tag:oZ3mddL0VRnQj++dORBnJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
