apiVersion: v1
kind: Secret
metadata:
    name: config-rl
type: Opaque
stringData:
    secrets.json: ENC[AES256_GCM,data:pTFvARFA2YRdVHCRzyOlAvn/l7O81y2xKISNpNzfP1FKPdL7MAgXJJaSBQI0Mxth7x+WwvwXLbuNlfX0iOQd7Ji6lD0Y7e4xNyE+ltIc2qmw89w+x4l7BSSHSZeOIdRhRDu1DzUZ0Q2e4KbDApf2Nf6nl9/jmZaNBjsuJXZsLZObkvyvkE29LIl3zG73vryxnoaHjFkpjZ5R0kxgQIhQfFKs+ON8CseNSqlm6Ms0rHrWJpj/eLnevDPAd0Bg95Tij1qyCEDpMda28vhhIluSw57pECFiOuhdmCJ9NZYqCMjUqTSawL33Wtxqnvg=,iv:0kh3HCa05esYmY4qhKZheIKn7d/kVYHF85z0BJ46lO8=,tag:z4IYRzF+w0Nw68ZePPi7+w==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNnFndG83dVVhQlIvWk0z
            SEJrbHhBSThGaHE4dU5WUkpLSGhQY0pMMVJVCnBBWUl2WVliUVRMVWY1Q0p5Y3ZW
            Q3pjSVgrUWM1NlQwS2swVi9YM3BmMWsKLS0tIHRyZTA3bUVEZ1FvcDZsbGhMR3lU
            SUlGMWlYN0FjZE5FMWhGWk9vc0pub2sKEgQ74TZiYjx/pd9SgLYPirIpz/f6ZJsb
            TGjq1wBkmwlGbLs1bCLNcL7yLv80cYvxmit3r8Bo26e9t7hbF+Mj5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SVJ2aTRlNkY4d1N3With
            R2FXNzk3VlF3OGtBNG9rVmRrU3dJZ1FkeEVFCmYrWm1BTW9ldjlCdVVlb1c1eDZK
            RXM5a0x6NENiY0ZubGVFRUVCUEpxKzgKLS0tIEdRcTIxZTVpWnVuY3FBRTRxSWRI
            OG5YZ28rRHVONFpVWnRHTzdoR2VBbGcKshhozjqiX0hPUhrycMIKlWiwm+urcyG8
            +rsM6M6TMLahHjYQ3bSbljIpf/FDXsbn0K23IYfEO+4Xpcwj2LszFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNDlYZjY3M3RTbm1iSlkv
            d253NVhzMzlxNW1UZFZjM09pWEFCcnJGbno4CjgyWWdtakFvKzZKajhwOFpCZFdj
            QnlCTlJ5T2k3RG5EWmdnWS94eFYvNTAKLS0tIDU5WlNSbUY0RDNseVFJanFNU2VR
            TGt4Nk9uR041MlQybngvd2FNRzgzcTQK6Xoh55zAbAwfUvq26AY1nW8TxdH/dW7a
            2DIFxp/e4rtXnVCgzLaIc8Nrp1bif7ExQ7qJYlISZIvNXMpncV7NoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSU4xSmZoWW9LYWlpR2V2
            RW4wRGxQbDNINjk0NXZybWVFMDYrV3BxTTFNCnpqZlpEaFBiVSt5ZWxuT1dCQllE
            YTBDdE9tc2pYd2Jmd0tFL1BvN1VvakkKLS0tIGl1Q1ZRemZCVW40TkNMcXRDeTlB
            M3FLOGpSOTE0YW0zT2Jja3cvb2N0amsKBdQugbtgSHqmHqTS9GMYtm/WdV+jTclv
            nwC68xGcNJ1Uap9sZI6mRFJnTKP+1Mpvg4rpoozlpVlex6qZwjpl3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:34:51Z"
    mac: ENC[AES256_GCM,data:lWTO6cdBYakkfiALSioJtUntEpEOur4h7O0579gvukv3r2kRMS8+IckRr+VirLOCOQZqD5HQ7/QE4eK9MPJGHmMBPML+WAwTuljAST20Jw2Cez+k6L6a2D+Dq3c2Gf3J16oJ4IiSpS7o1klJeZnvVo5SFL3vAkhKPKE2zb4c76c=,iv:3BAROZcwO5tsWyp9j2q4U2USi5knSFNlZE5r20JJ7vc=,tag:mhlb6Ifhu8ic/rI6Ig4oFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
