apiVersion: v1
kind: Secret
metadata:
    name: config-smash
type: Opaque
stringData:
    secrets.json: ENC[AES256_GCM,data:AJ81GR30p2C/Pjvm2A8+KQRYbI1SS4w8GnPPrdT9olYaBmXf175BzAZpYM+tXzJTGcYy39XnNfnqY1JyWqY7R61zybOzuMgaZJqYOeoqObG4iWYDGekIHJPKWHYjUzD57gU1ISp0PPQfBHB2zaLRC5aChv0aPq2VenAfbQGP0KNcV0jfcXfurUgEvtSRjH1NKrC6HuLV6xCE9+aV2oi8N1GZuUtX4w/CJAqZvSEHZS0VhnAlG7OXcQVRJxuZwT3CyHFVqkCDV/TDrS6ZEKjSJPsMxqce4VPxVczG3O5sw2VKyIIcSJcZb6BLfksdQg==,iv:kkg/+VOycofddNq6XIiDXzW231RRhDXm7Bw21V+0rl4=,tag:/o6pCksHUunxoX8P8bslvA==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OGUxa0xkWVNYY2tuTmc1
            ejF0NWcvejFGS3RVYkE3emxZbHhyRTRlbnl3Cno5RzRMMTA5TU1wdGVwUS9idGZK
            dVBBSWlZMk41TFFKVTRBMzBheGZ0SWcKLS0tIEtGaW5hMSt6VjhUMFYwRVdHS0wx
            UWRhRUtQOTEwSE9iM3J0K3dWN2lGU0kKwR+U0jXdePm5VB43mzKp32fT0zXr1VuP
            NEyACtEfs9Xmqr01zFuNMMnIBDRkvjynuEq+zA3Tv0qI1LvCCV3N6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aGZtT2dtVVF6ZmR3NStL
            Y0VUZ284aXdsRFdxQTcyM1owZWl4VE5aSWkwCmEwWnU4VnRXd2hZRklGNjhESkds
            U29vQ1BKUTNyMVg3cklUci9mWmxma0kKLS0tIEF4QWxUc3YyN2hwMHNEdDZCTFlr
            Z3FueXdXdGtDMHUzODk0ZmJIUHRaMTgK0fp9yIY4ybj+41hJwe+YN0UoBHiyEheB
            5wHpdRoISqAQcZNM2bgdl5OdaCGL+AKs26IuZO1PXxLASJQGMzCuIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqLzBSNVhrdEJCNHBhdlNa
            NHpKL0hMNHJ2WSs1TWh1WTFwMDFoS1Z2eGlnCkIrSFo2dm5GUnVpcHlsRXFiR1BI
            czJSc1I5L0pSMDVuVU15c3Z4QnhUQkkKLS0tIHZ4UDMzdFhzRmhWbXNBeDhLd2ww
            TWxyZk1nWHBlK0JUWWJ6dlNHVDBrcWMKbPr7P1lXFkFdlDez9+++EFL72iJKteXT
            wcUaZaPqKYijI/Vzq0q+OK0jQELStG6VPA/2KGgDYH+9FEorRvF+yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bnBrVkVNL1gvWkFwR3hr
            VVgvd0xMMENrbkdDalRlWG1ON0UzQmttcEJVCkZpUVFnY0RiWHdqT2FnVDJtWGlF
            T2lwZTlyVEJEZXpVaGFiRHQ2WVBBdGMKLS0tIGZhUjB3dkRrMEtDdmdKMS9BR3ZN
            QUFtd0NQb0t2c05OTzdneVlncnA1UnMK1TUcVXp9q2/E36pL2XWTBh+tshoKNYdr
            J3uVDOjyrkOsfFJE4xJG1vjT9JiYZhcBzFbgtWOvo+fsEcazHfH3hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:34:55Z"
    mac: ENC[AES256_GCM,data:IFw61vG3NJAlWyDNXxP2sh7ZwcfkB7RwpmB0qJSCqMjYcDBYuSbNbaODgZBKILCicsBh32p6qIhagkizDbJxbGzSn6sg3l7h/uBRGkHOxfaiTs+8Y8wT4LKX6hP34fZLXxpzog2se6lKG4a6crAZ0yub/+1sWOdS6Wol02FrxYQ=,iv:uyt5lDT2US6EiqmTmt1PmRRGbciBF+d7dwONNxuWl4I=,tag:MaTTxhF9CptfCt8QofPVSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
