apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:w3rKjl4yrC7RQf+otS0rgQpOuTwU889OgXk+kvXF7YU=,iv:tq2Mkv2MbtQt4CIsn825EmfIyfYP2aMV5PADQgoz43A=,tag:JeVZv/8KXXAJ8H8x//6zTw==,type:str]
    root-password: ENC[AES256_GCM,data:y7AsOChsZAglFME94JWMoY4+KLgjSmvD4zXHMd1bsBo=,iv:OxD5/UksDGieY0awOf9t8PpNnaDkvbJC0mAZAVvbGwo=,tag:On885f5y6WmBKZb+NUsfVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV25UcklpaTFCdTBNT0VO
            dE5EeVpTUFVkckRrZTduS2J4NDRoY3ZFKzFZCmJveDVYR0NubHJpUWtPWURISzNY
            aFBBMzhsM0lWK0lpNTh6MVNXYWx0WVUKLS0tIG9iUUt2RXhadVVRaGE4TUNyamti
            VWJ4Rmk2MkVsWitJcEJlclRBaGFTRFkKTjnmeHlsAx2C68gebwzZXgSUCsZQLc2N
            du2BycZXishzdcvFfydBLRCsloAhtVNZm9by0nZ92Vb33zDIHLpSzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeUswU3g2dU1IaEdDRGpk
            alRxVnk2dU5NUTM0Rkpjb09SUlk5aWo1a3hrCm9zRUFuVm5GTmZid29VUG84MmRE
            UkVkeElJRWg2aWU3bEdpekNXRkc5Nm8KLS0tIGRRTXFBR1VqaE1XZG5iRmVSOXdC
            Q1dCR2MrUHdaRFhHTEowdEJTcnZHTFEKqM2LgkTeKjaiXb8jsORsJPIwUGt3ybvJ
            En9sqNjowX1jL36v4p0DvhvpTQ8AOUCLJ3Cd19tWa4SFEZyyjwRN/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWWFUWUNlTXJ1a2tkbFZG
            U041dWdmZWhva2ZIZWN0U3NzTjJBNTFSODFzCktlYkM4TzhGbTVadXpGdFQ3NTBU
            UEVybjMvZTVWWEZNRFh3R0xvYmNVc0kKLS0tIHdZL3pWWFI0M2ZrOHd2SlIxZkRZ
            a3QxRDQzUFpyN1BHbWw2L0E0RzhBNEUKe7fiURXgSjj6Eoae+ZRcrC7ZmCBdkVXK
            ji6F9nwKcFroLX5euB4fUWjMLCKY1LIJ+hERBsqlAux/aD1u4BeOQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeUYycXVDYS9mdzRrUmo5
            SU0vZXAxRHdvUnltUGZ2MmIwalZ0V0Qzc1VVCmErV0hGMSs0MjdRZTIrV3RWRU8x
            NnBQUC9OcTE2dFg1UERJaEFpWUU1azQKLS0tIEdoOSswdlFRbEhyMVpSaVBYMHlD
            V0tlazh1RERZNUJhVDBDUXp2NVNDbmMKzbS04iEI94AroC/XwzV1tUKhMMKAELwO
            ilz2G9ktcv0yObe6TGmVCWN1UJ0TmyrIJjjC73On2Uq0xAMfcJiNwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:18:54Z"
    mac: ENC[AES256_GCM,data:U8TX9+KT3uVJD/DDg3zLYpWq0hq3Driw6ybH3Updx5/kg1dYDswmCesjHT1//TQYCE/8YQMZcX9wKbHxlpA+pIUrFWJnqUpuxWtn2I8qlhjQDyWnGNoEs+/cBWBPkPjf3ItqCJ6FDEa7ME8OXVwpbX634NsbHYd8MfHRp98FFcc=,iv:zM1VVs2VvfGMVImPUeeF4JMaeLJojrDihgsMXda3LAw=,tag:1i/VGJ4PJD2F0txx2jutag==,type:str]
    version: 3.13.3
