apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fleet-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/yoyozbi-homelab/k8s-config
  ref:
    branch: main
  secretRef:
    name: ghcr-auth
