apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ocr1-apps
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system 
  path: ./clusters/ocr1/overlays/apps
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
