apiVersion: v1
kind: Secret
metadata:
    name: activemq-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:H+3QG1s=,iv:y83rViVjis3TlIsjz4L0d2i0JS795Hl1itJCRUk6hIc=,tag:6zuAFEntLIP0ajZbAxGvjA==,type:str]
    password: ENC[AES256_GCM,data:FNdtltLCz9/cUVx7HGE+wlh9QQ4=,iv:gY61RYqHATMhxrNroLx8jdYWyfGEY0QHsRN/qNiIfMY=,tag:zgGaaRGcsvWzAcKyLzXgNQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bjNMNk04YlJFZjNHMWJk
            RnpOd3Z5YlkxQlhZSU1udCtrRVpZSDlZUngwClpKd2cyTEdONlRqT292eTNOMjlX
            ZmF1cmRhRDFjaE9Ob0IxNnpNNkJlNncKLS0tIExheGpaUmU3dzAzZDFDSEdFU1VS
            NHBtZXUxZjJuSTFDdDExeDRWbkJabFUKo1WvKtK0CPbIzP1iGlvTfnAA1OR9l0ps
            QnAVWFWemZluHn2SffvcAxfvWA7cygmPJ7FEt8wOFP0Ek++voVtfEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVJ3S1ROZUFqOUJZY21U
            U0JjdStWSXNFM0hYeHA1b0xuN0dKelJ5K1JzCjhXeUQwQmlvZ3MyY1F0Q2sxNFZ0
            SjdJa3hOOGV6YlE5TUpRck40OTRadlkKLS0tIDRZdzJ1MTY5bzFiNHlKcC82VGNW
            M2liVDV6NUNuRDZHZ3pLSFlReVQyZjQKvnhKUnN7s9ZOqe0yoYnEzr5rK2KPPYHb
            DojPs/t8XGMmzda+b4g/IS3orUMNMd2hFe91qZLVqyAuztp/sa6uzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSDYwblVCOVI0a1NRZ0l5
            RTZhL2lCYW1SQVFuUU9qSGcrczZrZWx6L1EwClhQQlVwc3dSdHJxUUgrUGNRVXNu
            RGh1dEZqeklFRlY3czVmTHNPQytkUnMKLS0tIHVya2FUQ0dReU9HSGVhVXhnOXpM
            K1BEaGxCTGN5Y29OTjZTMEhYaGZpRHMKSvj4RJUdmmcUsOEo+eGdikBS2kw6htxx
            eYRctY26nIphDclYVmvhpjMZ9s5d6eyXniwvMvsKmiwmUNnUxswWxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cVluUytUWnArajFDcU9K
            U0orRzdOTkxFS0RBWEZ5M3B1aHJlNThGNlJJCmh5TDFERXNlazNkVnVKYkZYamx4
            K2RkTUhmWXZxa0dLMEkzMlk1U1c4ZnMKLS0tIGRCa2gxTVZVZFczditJUVkxYVRk
            TmxTWWFLSWxGbXhTc3pCcjViQkVVekEKSxbWcPoOxzj2TByK+leASvYHceiD4XNI
            M3orHVwJs+F0dXy29JTJs/tAP9xxb6s6IzTyfSSc1clUNi8VUv7dhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T13:36:17Z"
    mac: ENC[AES256_GCM,data:IsZij7oJrxNvQWBwURNkUXDB1ORWjS9f/SzliTivrGi6sKEbwWDWA+0rK1TA48kZl8XxpCO6xJK6xZ/X/CfU6mk8M83YLvPb8JoUGoktpN/a8yNj8z9iNUHLNBsigsPwQgm+2zfD6kz0fW1zRu5GJSaefeUiThAG/9f1eL8aDug=,iv:A8cugtN4POOi35WncFmYlo1EGIePJPKlR5icHJLn/rg=,tag:g9iMNSrXsAXTF4GdUJ0mHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
