apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyseerr

resources:
  - chart.yaml

commonLabels:
  app.kubernetes.io/name: jellyseerr
  app.kubernetes.io/part-of: jellyseerr
