apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyseerr

helmCharts:
  - name: jellyseerr
    repo: https://loeken.github.io/helm-charts
    version: 2.7.3
    releaseName: jellyseerr
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/name: jellyseerr
  app.kubernetes.io/part-of: jellyseerr
