apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozzle
  labels:
    app.kubernetes.io/name: dozzle
    app.kubernetes.io/part-of: dozzle
spec:
  selector:
    matchLabels:
      app: dozzle
  template:
    metadata:
      labels:
        app: dozzle
        app.kubernetes.io/name: dozzle
        app.kubernetes.io/part-of: dozzle
    spec:
      serviceAccountName: pod-viewer
      containers:
        - name: dozzle
          image: amir20/dozzle:v10.9.0
          ports:
            - containerPort: 8080
          env:
            - name: DOZZLE_MODE
              value: "k8s"
