apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

bases:
  - ../../../../../apps/vaultwarden

# Include cluster-specific secrets
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml

generatorOptions:
  disableNameSuffixHash: true

# Cluster-specific configuration
configMapGenerator:
  - name: vaultwarden-config
    behavior: merge
    literals:
      - DOMAIN=https://vault.yohanzbinden.ch

secretGenerator:
  - name: vaultwarden-secrets
    behavior: merge
    envs:
      - secrets/admin.sops.env
      - secrets/database-url.sops.env
      - secrets/smtp.sops.env
      - secrets/yubico.sops.env

# Cluster-specific patches
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: vaultwarden
    patch: |-
      - op: replace
        path: /spec/values/ingress/main/enabled
        value: true
      - op: add
        path: /spec/values/ingress/main/hosts
        value:
          - host: vault.yohanzbinden.ch
            paths:
              - path: /
                pathType: Prefix
      - op: replace
        path: /spec/values/persistence/data/type
        value: persistentVolumeClaim
      - op: replace
        path: /spec/values/persistence/data/existingClaim
        value: vaultwarden-data
