apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployments/bookmarks-deployment.yml
  - services/bookmarks-service.yml
  - ingresses/bookmarks-ingress.yml

commonLabels:
  app.kubernetes.io/name: auto-bookmarks
  app.kubernetes.io/part-of: auto-bookmarks
