apiVersion: v1
kind: Service
metadata:
  name: pollenzo-api
  labels:
    app.kubernetes.io/name: pollenzo
    app.kubernetes.io/part-of: pollenzo
spec:
  type: ClusterIP
  selector:
    app: pollenzo-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
