apiVersion: v1
kind: Service
metadata:
  name: pollenzo-fetcher
  labels:
    app.kubernetes.io/name: pollenzo
    app.kubernetes.io/part-of: pollenzo
spec:
  type: ClusterIP
  selector:
    app: pollenzo-fetcher
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
