# TODO: Run `sops -e -i app-secret.yaml` before committing
apiVersion: v1
kind: Secret
metadata:
    name: supersync-app-secret
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:ej7czNWzWCLMpDCP3iySYUfpQTisSJCYIQ==,iv:r2KhanjmWmDqWEfwSLnxS5qIa9HcvnzrF88ujSJsCGI=,tag:oIzHzFnqs+Hp+IIlQD3hIA==,type:str]
    smtp-host: ENC[AES256_GCM,data:lpXGGllhESfco0dDhfmFBgta8Q==,iv:MV34/O+8wYaqG0+hevUj4ihjtzHKLl7D3Upq8b04zJ8=,tag:M4CYqLzqjRO/GgPyLwDCMA==,type:str]
    smtp-port: ENC[AES256_GCM,data:g9o9,iv:DShDJpdiRFw9furRQzH/OJVwWb7fLGGjXifB8pYpgyg=,tag:RcX/mH+dpFg6/OdoPYa1NQ==,type:str]
    smtp-secure: ENC[AES256_GCM,data:ZdNCET9WzRMV,iv:UP+HKQatVa7v4rsN3AsFvnJ8gM6YqRWNtipMH/s8aX8=,tag:FWIenWfxnfrZb3v0rvx4Og==,type:str]
    smtp-user: ENC[AES256_GCM,data:x4ZsEyNNQmJp82ZwoFfk0mgFT1mT,iv:at0AIyntjz5UPAzkSJ8y8TxeVa0+66TJhgkvY6KC9No=,tag:wmRGgherpHKpeyL39+qjCw==,type:str]
    smtp-pass: ENC[AES256_GCM,data:LtnowJoQIdpNQxkUc+I4vd0=,iv:BP1El0OAMjNVloVWdRvAQvRPcWTesUAKWJyQiDgyxns=,tag:15KfdT1N7/E210Q2f+FWZg==,type:str]
    smtp-from: ENC[AES256_GCM,data:BU61OY1DS4Ig/ZUyk6Pi+myW6Jzn,iv:ZGLPlnxWbeZXRI/zIIpjfdjG2t6AJhEOEYlTJQr+2ag=,tag:qf+7NNDSLV5VvWO4eNZ2pQ==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMlZqWWNyYXVabmFQOURz
            aGtYd3MwazUrL3Fuc2pndDhKRGx5K3dweFU0ClY2dklrYXNhb0FVSnpHUmlqaXdF
            NUdpVEEyMmg3UVVBdWkzT2J1clIzMW8KLS0tIHAzUStVUUtneXF4enBTeEN1L0FR
            SzFJamU0TzFFVmlvOTlqQmYwdkQ4OWcKiiqgmyCDlnQf+siltuQLh6889JjDkPUn
            B4v+2YfeiHr8vTEbuteT2KCOMOwnJMMnRqZg+24p+eZiN2hhhaHB/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHlVaHFnczl0bkxKeHcr
            SVlpeG9NQTE5UkpLUVVVMjVmOWh0a0RKUEQwCnZHY1pueXd6SUEralFyTnBkQmhS
            anZLczRmanFPZFU0cHlJZ1VWT1FjOUUKLS0tIDJkVVk0ampKK0pNbTdkVnUrMDhk
            ZlZZYldsbCt1ZzZ6UVB4Z1RZbDBNaW8KmP+D2yCxWVH194tc58PP9I+BWdfwkb71
            KjfNSR6VuHqiXfBDAZYah5aqKABnjkyPyTk9Z79jVo9ud+1MQaXUiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYi95WkI3VGwybjc2cmxJ
            OWJYZ1VvZzNyUkFGZ3FvcWxnLzlMY2d5ZWg4CmRwTnJGSmZUWWI3Mk9JVXhoU2ha
            YjhoSDRhQjU2NjhGYVZzRXpndy9iancKLS0tIFV4UFhJYUhydUJ5alBHOXFKOHdn
            T2hNTmx4bU52MU5MeFVPOGtXbExraVkKQqGO0AH1IoEAB+g4NZRIA8Ze4li8yPpG
            unU/mn86exTp8g4W2+oqhnwaiS2a0YF0qnS8+lkjHOnouantZ4oJyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdG9GWmd4ckpJeXhSWkcy
            M0dNVmhKMTh6WjJ4UGJOV0o5SGMzZkhzY1JrClBnZk0xVzJrZlR6L1BlYkJ0V1ZR
            SEk5UHQ1NWVhK1oxLzhTdGE2cnhBUWcKLS0tIDhWMUxHUWRuY1ZPSWZ4WjB0ek1k
            dDVQbXZRNkU2ZEtmZzZTR3pXMEVPZVUKwzFKrl2k6m2WKqEbl6N/3pSFN+TU0UZh
            w3jKBYcoX1cOoXFonoSS74RwBD1xMTDgojkGdjv+0WlMIAScihZsvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T09:31:56Z"
    mac: ENC[AES256_GCM,data:/0T5dRDbFtV+34SwhwC4TFzSm8O2W2f9mkm1uJG4mDIg1HK0TV6WVGT+i8OEVGxCWnweseNV0HhY5MTGszWxkiZ7HA5fB1tw7VQ+XaHLTXOht4s3JBrYK2Ol64T8aS+7SKrGH99Ohb4v1tQsTwAgQuOyQbzwmq2tVKhdIAd04ao=,iv:P/zUuqu8j9wB6BLBStahyn44vATjbAmE09eoO2yEd4U=,tag:g+JTqZ/FhTOR48c6fyxTiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
