apiVersion: v1
kind: Secret
metadata:
    name: supersync-backup-config
type: Opaque
stringData:
    webdav-url: ENC[AES256_GCM,data:RrMvv0AJgPMQqeT0SDYp16EYdlygFIzXz15rQg/fwDbTOQWzCF+v+A8QSs0ewuLwsjtOg3mTeQ+cpNk3mg==,iv:V7EyFjYZKFmLx6JKUnRBHzB6Gw9HoFRJ0uCBNu3xHis=,tag:joRNZTsfgzRO8fbKXcj/xg==,type:str]
    webdav-username: ENC[AES256_GCM,data:vZEGylf/sn9ZwlUC+DiOwTetObC+sgo=,iv:zobZNUgxVcbXvum1FJ/d75noPnQ4m4SbJbFy28r6xk8=,tag:kaW2jEC/JiDRfT8nNzp9LA==,type:str]
    webdav-password: ENC[AES256_GCM,data:5HjYvF/CLjQ0p56O4Xfqdg==,iv:zjWfkQp4TM/MAUBJz6H40aICLARDSdMIyXSBiwprbdY=,tag:+zaFSQXJoYiNInSUgSb0zw==,type:str]
    ntfy-topic: ENC[AES256_GCM,data:pJghRYLClOA6YdULAiZtfvrglH0+Y2dsY9tlQrL7MRQ=,iv:nYz1It0gAWwUD0EkArghOpsjuXQWlY+oSN6+WKtt67w=,tag:ll45G0gS0oebINm20pHRmw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSHl1RTZGZzFhQXJ1SnZG
            MHZOYjJ6NHBLRkEzQXQ4WjZmQUpwMDBGanlVCitPUVNSclBOOW1XYnFkQ3dobVd0
            K09ibmM3OEF3SFVRV2FNRTlqaTZrOUEKLS0tIDh0dVp1dk9WUm5UWllrMkZEZW4x
            VUxRaSs3SjBFcC9ibjRWQi9wMXd6VFkK2Ay3+coeOCB5WbmD2xjqT4wegSfRa1DH
            Su53GANtKqk67e+quHjf7uXjyeDilFDK7zi4JfzxhS88VR7fHdxuog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbjQzd2ppcDR3czNFbDRB
            ZGZ6SVpjaEFFQTA0cG9uU3g4ekZrMWNmWkRZCmhtVnh0T2hUd2ZvZVQvZ1RxaTNG
            TGNUclc2ZFY0T1NsTUc1SDdJL0pYdjAKLS0tICtTeUh0Y3VjQ1VyV3NFVittUXE1
            YmllYnFYSmVwc2hGMHI4TzU1aEQ2d28KqSSHkbP4Np/6sAnTfD/4w8HOPb9YNSkE
            kRozRym/rDups7Xn/hqIokfe0Lu5wJvfxKze3XwVAxP94riiLHnmkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR29UWERXc1RhY2U4MU9s
            RnphU043M1lSYURmOE9oK0o1SGZ4Yms3QXhBCnErOEk0YVNqQTVUaUtrU05aWW1D
            OG5YN2lpbzlZc2lGVU9sK0VVM1BuRHcKLS0tIHNCc242amZHWktkeW5SdU1xbkxS
            SkR4ZTduRk1NWjljUmVKakJ2WjhpRkkKpKE5froSVOA04vq4Jeugr8hWIbgEvQh4
            YSYDItRCVTsL4oSsDIqJTdHxuNhBB4ypU0W2lSG9eODjkHCxj+l8rw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z0YrdE0zYXFhSHJDeTlQ
            U1krTlo5WGszTVYxT2lONXI1OUtwNkV0MWcwCkd4QmtrdEtFTVhmOHkyS1dPR01w
            RkVLbXFRdTJRN05odXFKeEo1ZEU2cmsKLS0tIEYxOG4yaU02L21vODJ6NFo5WFVP
            SnpJVlI3RmNXZmFHNUVQZnhDaHdmYkkKdgPA+1Rw7Y3TbTpFqRjJ4TNslH5Zq9iU
            iY+YjhLnr/u3j+dFs03WAU4Qxoz+3jSmVuZWATny5FxiuI9fxNZR+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T09:32:00Z"
    mac: ENC[AES256_GCM,data:9zfrLdA5eEPZNH/WXYpW+3MaXv7RWash91OE0tGrWFUfVXByoXK4tfm+Ycr5o140Hgjr5zePOKfYwJF3Odh/UjEtd3tTABEVB4cvigbxPk2878oA2GjHy1xR7b04NRJlaelcMgZGpS0cnmA6+wqkxneBGZuHxXzFOsbZejw9Sm4=,iv:+qlwTacnmpoCuTqMMaLnnotSN6F1QRhFD6LBG1/XyxA=,tag:YmWT9RuSfJxhHXixxIRpmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
