apiVersion: v1
kind: Secret
metadata:
    name: supersync-db-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:jhoP0dapwF1C4bv1VjA=,iv:pb4DXAT+2AwTvShuZylqKNb7583bkKV1RxobrUqnF5U=,tag:TNEST9LvmXd1PlD7eDTYPw==,type:str]
    database-url: ENC[AES256_GCM,data:wLUrbOO3b3Azxh7KCwFHSYX32d1e/5kCwlc/ZdEo7J/hObjERw8XDeckLlgEru1osNIAVKFgqe94KlpL2yNPdP7be7su+8rGWKJksjOLgBY4PW1gfcZvQY8tgVRDS21j/GM=,iv:8hMigWvxebQJJNuoXxMImw6afAuEbh2Vp0prQSRmAn4=,tag:7lb52A5HD8zl/kUe7bZ/Vw==,type:str]
sops:
    age:
        - recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDU09Qdy9kMXpFbGtKdEtX
            SFl6emcwMWNUZlIvRnltWHh3MGRwdUo2OW5vCkV5Rnp6RTJqcGkwVG50TXlSQkhy
            dllpTHdMczcrN2RqREErbVBxT2hOTEkKLS0tIG43VmJGWnAvOHJwRGFXdnhCTFFF
            dGVkdXQyQUJiN0lSdi92K2YyZytjaVkKUrGcLDIpd+F1pxv9u3HOZXSdatY6tE5V
            ijwLTryVFqHHCTmFhb3fcai2C3PGqM+rKUT0DKYFHRXSDlNIxmBUqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsc70q3w3qdscy2vrjy6ktrsnj3l3pjrgk9yt2j8c7mcmc0x65es79mm8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbzV3NE1GdXN3MnBaL3o1
            OTFsOEdzNG8vMnJtRFI4czJidmVQRnhFdHlBCkNYbFd1OE0xNlNQYWZybTNYQW5Q
            VWhCNklLUjBrenBYeHcycWZIa3F5MzgKLS0tIG9TQlJiUzRkY1J0NktmamFJaE0x
            aVFQL2dxaXVsemNCMUtTdFlGWkc5VkUKdE2zri0WR5M654pnqsuo5LiqlQG2JSBG
            iscv+axsFb4vom6nWnL7v7yDV0NQlvWEWwlo2pQxOC6NI1W6SOs5IA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qvtyyp98sf4ncmdev0uf3mdes7t48epny7kn85d4k86awjzs8qxq5mkh9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdndlMFpubHozeENoRk9W
            R09qZG1oRGsvblRCRG02N0puL1ZvZVhsN0Z3Cm1aa05sSmxuZi8zTHFLNTR2dVZC
            dWpUS1Z3cTFhWDZDQ29qOHJkTUV5OFUKLS0tIGtPUGxLdUh5VFgxVDdYRkVRd2ZE
            MlAxcFRsT2Q3SEZ5UjNkRHhsdEFjdzQKe6yHTZOKkwob3+DVlzxP5NR5QRM0+hxg
            9kDzTsLEoI3I9keo6zJkdOpKPtpSf/xBzlEvC/WzywmsKyrmPvAEaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdHNmM29vNlc1TE1YZlU5
            b3FabkxMUHloQ09nV2hPRWJTaEs0a0hhZnhjCjVneFZBRGpQcHllNHpYWUNFRlJG
            NUYzMUljTkhkejA3dFZKRDN1WTNYMVUKLS0tIGZoVG4raXRjTDcrVTB5QkdsQ01T
            ZVN5NTVFWld4amlKYkRTYmFzN2p6ZGcKdt3Xa+Ihoe4yR56QsZTrpgQ//K0JlF/v
            E8aWGHSbRMJ2T1kjHddnpR4Lvrxn+i+xS4xYolQJwFY9/7vtVEx3rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T09:31:50Z"
    mac: ENC[AES256_GCM,data:8AryJtzCnVGlXKlqpeqMxRYHRsqro83e+SD5o3/1SUT9GGE1w54s17tZ+j75TWCerEN5V38Ct8ZmkdfX3y4bLmBPrYQ5AsbZXtEY6FVCU8ybk+JBfE+NMMYtSlG1YMG7GBSmzNCxjQ580tbBwsciID6no79A7zqDxH047D0CiBs=,iv:WnatRyNpAjqjlMT2jIaR7piAT/b2WU3DTUW0+1n7YT0=,tag:AtYzbTGaEj316DdLDbz2Bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
