apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pollenzo

bases:
  - ../../../../../apps/pollenzo/

resources:
  - namespace.yaml
  - secrets/pollenzo-secret.yaml
  - secrets/pollenzo-db-secret.yaml

patches:
  - target:
      kind: Ingress
      name: pollenzo-api-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pollenzo.yohanzbinden.ch

commonLabels:
  app.kubernetes.io/name: pollenzo
  app.kubernetes.io/part-of: pollenzo
