apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pollenzo

bases:
  - ../../../../../apps/pollenzo/

resources:
  - namespace.yaml
  - secrets/pollenzo-secret.yaml
  - secrets/pollenzo-db-secret.yaml

patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: pollenzo-api-ingressroute
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`pollenzo.yohanzbinden.ch`) && !PathPrefix(`/actuator`)"

commonLabels:
  app.kubernetes.io/name: pollenzo
  app.kubernetes.io/part-of: pollenzo
