apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auto-bookmarks
  - homepage
  - jellyseerr
  #- niles
  - cloudnative-postgres
  - vaultwarden
  - vikunja
  #- dozzle
  - supersync
  #- activemq
  - newt
