apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

decryption:
  - provider: sops
    secretRef:
      name: sops-age
      namespace: flux-system

resources:
  - auto-bookmarks
  - homepage
  - jellyseerr
  - niles
  - cloudnative-postgres
  - vaultwarden
  - vikunja
