apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app.kubernetes.io/name: activemq
    app.kubernetes.io/part-of: activemq
spec:
  type: ClusterIP
  selector:
    app: activemq
  ports:
    - name: jms
      port: 61616
      targetPort: 61616
      protocol: TCP
    - name: webconsole
      port: 8161
      targetPort: 8161
      protocol: TCP
