apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - repository.yaml
  - release.yaml
  - php-config.yaml
  - mariadb.yaml

commonLabels:
  app.kubernetes.io/name: wordpress
  app.kubernetes.io/part-of: wordpress
